/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medical;

import java.awt.Font;
import java.awt.ScrollPane;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Sheng
 */
public class ModifyMedicine extends javax.swing.JFrame {

    /**
     * Creates new form ModifyMedicine
     */
    DefaultTableModel model ;
    private User user;
    
    public ModifyMedicine() {
        initComponents();
    }

    public ModifyMedicine(User user) {
        this.user = user;
        initComponents();
        txtName.setEnabled(false);
        txtComponent.setEnabled(false);
        txtIndication.setEnabled(false);
        txtEffect.setEnabled(false);
        txtScoop.setEnabled(false);
        txtWeight.setEnabled(false);
        txtCost.setEnabled(false);
        txtPrice.setEnabled(false);
        comboMedicine();
        changeLabel();
        createColumns(1,"");
        widthTable();
        JTableHeader tableHeader = tblMedicine.getTableHeader();
        tableHeader.setFont(new Font("STXihei", Font.BOLD, 18));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboMedicine = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblzhucheng = new javax.swing.JLabel();
        lblzhuzi = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEffect = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtScoop = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCost = new javax.swing.JTextField();
        lblCost = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtIndication = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtComponent = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMedicine = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel1.setText("药：");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 80, 38, 26);

        comboMedicine.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        comboMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMedicineActionPerformed(evt);
            }
        });
        getContentPane().add(comboMedicine);
        comboMedicine.setBounds(200, 80, 110, 40);

        jLabel2.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel2.setText("名字：");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 220, 57, 30);

        txtName.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        getContentPane().add(txtName);
        txtName.setBounds(200, 220, 480, 40);

        lblzhucheng.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        lblzhucheng.setText("组成：");
        getContentPane().add(lblzhucheng);
        lblzhucheng.setBounds(100, 290, 60, 30);

        lblzhuzi.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        lblzhuzi.setText("主治：");
        getContentPane().add(lblzhuzi);
        lblzhuzi.setBounds(100, 430, 60, 30);

        jLabel5.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel5.setText("功效：");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 550, 60, 30);

        txtEffect.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        getContentPane().add(txtEffect);
        txtEffect.setBounds(200, 550, 480, 40);

        jLabel6.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel6.setText("每次每日分量：");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 620, 133, 30);

        txtScoop.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        getContentPane().add(txtScoop);
        txtScoop.setBounds(200, 620, 480, 40);

        jLabel7.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel7.setText("重量：");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(90, 690, 57, 30);

        txtCost.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        getContentPane().add(txtCost);
        txtCost.setBounds(200, 760, 480, 40);

        lblCost.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        lblCost.setText("本钱 RM/GM: RM");
        getContentPane().add(lblCost);
        lblCost.setBounds(7, 760, 190, 30);

        txtWeight.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        getContentPane().add(txtWeight);
        txtWeight.setBounds(200, 690, 480, 40);

        lblPrice.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        lblPrice.setText("价格 RM/GM: RM");
        getContentPane().add(lblPrice);
        lblPrice.setBounds(10, 830, 190, 26);

        txtPrice.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        getContentPane().add(txtPrice);
        txtPrice.setBounds(200, 830, 480, 40);

        jLabel3.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel3.setText("ID:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 150, 30, 30);

        txtID.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        getContentPane().add(txtID);
        txtID.setBounds(200, 150, 480, 40);

        btnFind.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        btnFind.setText("寻找");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        getContentPane().add(btnFind);
        btnFind.setBounds(690, 150, 90, 40);

        btnBack.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        btnBack.setText("退出");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(30, 900, 130, 60);

        btnModify.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        btnModify.setText("更改");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });
        getContentPane().add(btnModify);
        btnModify.setBounds(400, 900, 130, 60);

        btnDelete.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        btnDelete.setText("删除");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(550, 900, 130, 60);

        txtIndication.setColumns(20);
        txtIndication.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        txtIndication.setRows(5);
        jScrollPane2.setViewportView(txtIndication);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(200, 430, 480, 90);

        txtComponent.setColumns(20);
        txtComponent.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        txtComponent.setRows(5);
        jScrollPane3.setViewportView(txtComponent);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(200, 290, 480, 100);

        jLabel4.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        jLabel4.setText("更改药资料");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(570, 10, 140, 40);

        lblWeight.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        lblWeight.setText("GM");
        getContentPane().add(lblWeight);
        lblWeight.setBounds(680, 690, 60, 40);

        tblMedicine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblMedicine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMedicineMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMedicine);

        jScrollPane4.setViewportView(jScrollPane1);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(810, 70, 990, 890);

        setBounds(0, 0, 1931, 1037);
    }// </editor-fold>//GEN-END:initComponents

    private void comboMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMedicineActionPerformed
        // TODO add your handling code here:
        txtName.setText("");
        txtComponent.setText("");
        txtIndication.setText("");
        txtEffect.setText("");
        txtScoop.setText("");
        txtWeight.setText("");
        txtCost.setText("");
        txtPrice.setText("");
        txtID.setText("");
        txtID.setEnabled(true);
        txtName.setEnabled(false);
        txtComponent.setEnabled(false);
        txtIndication.setEnabled(false);
        txtEffect.setEnabled(false);
        txtScoop.setEnabled(false);
        txtWeight.setEnabled(false);
        txtCost.setEnabled(false);
        txtPrice.setEnabled(false);
        createColumns(1,"");
        changeLabel();
        widthTable();
        
    }//GEN-LAST:event_comboMedicineActionPerformed

    private void tblMedicineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMedicineMouseClicked
        // TODO add your handling code here:
        int index = tblMedicine.getSelectedRow();
        TableModel model = tblMedicine.getModel();
        String ID = model.getValueAt(index, 0).toString();
        String Name = model.getValueAt(index,1).toString();
        String Component = model.getValueAt(index,2).toString(); //property
        String Indications = model.getValueAt(index,3).toString();//appliance
        String Effect = model.getValueAt(index,4).toString();//appliance
        String Scoop = model.getValueAt(index,5).toString();
        String Gram = model.getValueAt(index,6).toString();
        String Cost = model.getValueAt(index,7).toString();
        String Sellprice = model.getValueAt(index,8).toString();
        
        txtID.setText(ID);
        txtName.setText(Name);
        txtComponent.setText(Component);
        txtIndication.setText(Indications);
        txtEffect.setText(Effect);
        txtScoop.setText(Scoop);
        txtWeight.setText(Gram);
        txtCost.setText(Cost);
        txtPrice.setText(Sellprice);
        
        disabledTextBox();
    }//GEN-LAST:event_tblMedicineMouseClicked

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
        String ID = txtID.getText();
        
        if(ID.equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(rootPane, "ID没填！");
        }
        else
        {
            createColumns(2,ID); 
        }
        
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        MedicalDetailMenu menu = new MedicalDetailMenu(user);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        // TODO add your handling code here:
        String name = txtName.getText();
        String component = txtComponent.getText();
        String indication = txtIndication.getText();
        String effect = txtEffect.getText();
        String scoop = txtScoop.getText();
        String gram = txtWeight.getText();
        String cost = txtCost.getText();
        String price = txtPrice.getText();
        String ID = txtID.getText();
        String code = ID.substring(0,9);
        String result;
        try
        {
            if(name.equalsIgnoreCase(""))
            {
                JOptionPane.showMessageDialog(rootPane, "请填写名字！");
            }
            else if(component.equalsIgnoreCase(""))
            {
                if(comboMedicine.getSelectedItem().equals("单味药粉"))
                {
                    JOptionPane.showMessageDialog(rootPane, "请填写药性！");
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "请填写组成！");
                }
            }
            else if(indication.equalsIgnoreCase(""))
            {
                if(comboMedicine.getSelectedItem().equals("单味药粉"))
                {
                    JOptionPane.showMessageDialog(rootPane, "请填写应用！");
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "请填写主治！");
                }
            }
            else if(effect.equalsIgnoreCase(""))
            {
                JOptionPane.showMessageDialog(rootPane, "请填写功效！");
            }
            else if(scoop.equalsIgnoreCase(""))
            {
                JOptionPane.showMessageDialog(rootPane, "请填写每次每日分量！");
            }
            else if(gram.equalsIgnoreCase(""))
            {
                JOptionPane.showMessageDialog(rootPane, "请填写重量！");
            }
            else if(cost.equalsIgnoreCase(""))
            {
                JOptionPane.showMessageDialog(rootPane, "请填写本钱！");
            }
            else if(price.equalsIgnoreCase(""))
            {
                JOptionPane.showMessageDialog(rootPane, "请填写价格！");
            }
            else
            {
                if(code.equalsIgnoreCase("GrasMedPi"))
                {
                    GrassMedicinePill pill = new GrassMedicinePill();
                    result = pill.EditGrassMedicinePill(ID, name, component, indication, effect, scoop, gram, cost, price);
                    if(result.equalsIgnoreCase("1"))
                    {
                        JOptionPane.showMessageDialog(rootPane, "更改成功");
                        model.setRowCount(0);
                        show_medical();
                        resetTextBox();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(rootPane, result);
                    }
                }
                else if(code.equalsIgnoreCase("GrasMedPo"))
                {
                    GrassMedicinePotion pill = new GrassMedicinePotion();
                    result = pill.EditGrassMedicinePotion(ID, name, component, indication, effect, scoop, gram, cost, price);
                    if(result.equalsIgnoreCase("1"))
                    {
                        JOptionPane.showMessageDialog(rootPane, "更改成功");
                        model.setRowCount(0);
                        show_medical();
                        resetTextBox();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(rootPane, result);
                    }
                }
                else if(code.equalsIgnoreCase("TradMedPi"))
                {
                    TraditionalMedicinePill pill = new TraditionalMedicinePill();
                    result = pill.EditTraditionalMedicinePill(ID, name, component, indication, effect, scoop, gram, cost, price);
                    if(result.equalsIgnoreCase("1"))
                    {
                        JOptionPane.showMessageDialog(rootPane, "更改成功");
                        model.setRowCount(0);
                        show_medical();
                        resetTextBox();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(rootPane, result);
                    }
                }
                else if(code.equalsIgnoreCase("TradMedPo"))
                {
                    TraditionalMedicinePotion pill = new TraditionalMedicinePotion();    
                    result = pill.EditTraditionalMedicinePotion(ID, name, component, indication, effect, scoop, gram, cost, price);
                    if(result.equalsIgnoreCase("1"))
                    {
                       JOptionPane.showMessageDialog(rootPane, "更改成功"); 
                       model.setRowCount(0);
                       show_medical();
                       resetTextBox();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(rootPane, result); 
                    }
                }
            }
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "ModifyMedicine.btnModifyActionPerformed get error on line 464, "+ex.getMessage());
        }
    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String ID = txtID.getText();
        String code = ID.substring(0,9);
        String result;
        try
        {
            if(code.equalsIgnoreCase("GrasMedPi"))
            {
                GrassMedicinePill pill = new GrassMedicinePill();
                result =pill.DeleteGrassMedicinePill(ID);
                if(result.equalsIgnoreCase("1"))
                {
                    JOptionPane.showMessageDialog(rootPane, "删除成功");
                    model.setRowCount(0);
                    show_medical();
                    resetTextBox();
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, result);
                }
            }
            else if(code.equalsIgnoreCase("GrasMedPo"))
            {
                GrassMedicinePotion pill = new GrassMedicinePotion();    
                result = pill.DeleteGrassMedicinePotion(ID);
                if(result.equalsIgnoreCase("1"))
                {
                    JOptionPane.showMessageDialog(rootPane, "删除成功");
                    model.setRowCount(0);
                    show_medical();
                    resetTextBox();
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, result);
                }
            }
            else if(code.equalsIgnoreCase("TradMedPi"))
            {
                TraditionalMedicinePill pill = new TraditionalMedicinePill(); 
                result = pill.DeleteTraditionalMedicinePill(ID);
                if(result.equalsIgnoreCase("1"))
                {
                    JOptionPane.showMessageDialog(rootPane, "删除成功");
                    model.setRowCount(0);
                    show_medical();
                    resetTextBox();
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, result);
                }
            }
            else if(code.equalsIgnoreCase("TradMedPo"))
            {
                TraditionalMedicinePotion pill = new TraditionalMedicinePotion();  
                result = pill.DeleteTraditionalMedicinePotion(ID);
                if(result.equalsIgnoreCase("1"))
                {
                   JOptionPane.showMessageDialog(rootPane, "删除成功"); 
                   model.setRowCount(0);
                   show_medical();
                   resetTextBox();
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, result); 
                }
            }
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "ModifyMedicine.btnDeleteActionPerformed get error on line 529, "+ex.getMessage());
        }
        
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    public void createColumns(int count, String ID)
    {
        // count 0 就是我们一按进这个page的
        // count 1 就是换combo box
        // count 2 就是按寻找的时候
        model = (DefaultTableModel)tblMedicine.getModel();
        if(count != 0)
        {
            model.setColumnCount(0);
            model.setRowCount(0);
        }
        if(comboMedicine.getSelectedItem().equals("单味药粉"))
        {
            try {
                System.out.println(1);
                System.out.println(count);
                lblzhucheng.setText("药性:");
                lblzhuzi.setText("应用:");
                model.addColumn("ID");
                model.addColumn("名字");
                model.addColumn("药性");
                model.addColumn("应用");
                model.addColumn("功效");
                model.addColumn("每次每日分量");
                model.addColumn("重量");
                model.addColumn("本钱");
                model.addColumn("价格");
                model.addColumn("更新时间");
                model.addColumn("创建时间");
                if(count == 0 || count == 1)
                {
                    show_medical();
                }
                else
                {
                    show_medical_ID(ID);
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "ModifyMedicine.createColumns get error on line 573, "+ex.getMessage());
            }
        }
        else
        {
            try {
                lblzhucheng.setText("组成:");
                lblzhuzi.setText("主治:");
                model.addColumn("ID");
                model.addColumn("名字");
                model.addColumn("组成");
                model.addColumn("主治");
                model.addColumn("功效");
                model.addColumn("每次每日分量");
                model.addColumn("重量");
                model.addColumn("本钱");
                model.addColumn("价格");
                model.addColumn("更新时间");
                model.addColumn("创建时间");
                if(count == 0 || count == 1)
                {
                    show_medical();
                }
                else
                {
                    show_medical_ID(ID);
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "ModifyMedicine.createColumns get error on line 601, "+ex.getMessage());
            }
        }
    }
    
    public void show_medical() throws SQLException{
        
        if(comboMedicine.getSelectedItem().equals("单味药粉")) // traitional medicine potion
        {
            TraditionalMedicinePill medic = new TraditionalMedicinePill();
            List<TraditionalMedicinePill> medicList = new ArrayList<TraditionalMedicinePill>();
            medicList = medic.getTraditionalMedicinePill();
            DefaultTableModel model = (DefaultTableModel)tblMedicine.getModel();
            Object row[] = new Object[11];
            for(int i =0; i<medicList.size(); i++)
            {
                row[0] = medicList.get(i).getCode();
                row[1] = medicList.get(i).getName();
                row[2] = medicList.get(i).getProperty();
                row[3] = medicList.get(i).getAppliance();
                row[4] = medicList.get(i).getEffect();
                row[5] = medicList.get(i).getScoop();
                row[6] = medicList.get(i).getGram();
                row[7] = medicList.get(i).getCost();
                row[8] = medicList.get(i).getSellprice();
                row[9] = medicList.get(i).getLastUpdateDateTime();
                row[10] = medicList.get(i).getCreateDateTime();
                model.addRow(row);
            }
        }
        else if(comboMedicine.getSelectedItem().equals("复方药粉"))
        {
            TraditionalMedicinePotion medic = new TraditionalMedicinePotion();
            List<TraditionalMedicinePotion> medicList = new ArrayList<TraditionalMedicinePotion>();
            medicList = medic.getTraditionalMedicinePotion();
            DefaultTableModel model = (DefaultTableModel)tblMedicine.getModel();
            Object row[] = new Object[11];
            for(int i =0; i<medicList.size(); i++)
            {
                row[0] = medicList.get(i).getCode();
                row[1] = medicList.get(i).getName();
                row[2] = medicList.get(i).getComponent();
                row[3] = medicList.get(i).getIndications();
                row[4] = medicList.get(i).getEffect();
                row[5] = medicList.get(i).getScoop();
                row[6] = medicList.get(i).getGram();
                row[7] = medicList.get(i).getCost();
                row[8] = medicList.get(i).getSellprice();
                row[9] = medicList.get(i).getLastUpdateDateTime();
                row[10] = medicList.get(i).getCreateDateTime();
                model.addRow(row);
            }
        }
        else if(comboMedicine.getSelectedItem().equals("药丸"))
        {
            GrassMedicinePill medic = new GrassMedicinePill();
            List<GrassMedicinePill> medicList = new ArrayList<GrassMedicinePill>();
            medicList = medic.getGrassMedicinePill();
            DefaultTableModel model = (DefaultTableModel)tblMedicine.getModel();
            Object row[] = new Object[11];
            for(int i =0; i<medicList.size(); i++)
            {
                row[0] = medicList.get(i).getCode();
                row[1] = medicList.get(i).getName();
                row[2] = medicList.get(i).getComponent();
                row[3] = medicList.get(i).getIndications();
                row[4] = medicList.get(i).getEffect();
                row[5] = medicList.get(i).getScoop();
                row[6] = medicList.get(i).getGram();
                row[7] = medicList.get(i).getCost();
                row[8] = medicList.get(i).getSellprice();
                row[9] = medicList.get(i).getLastUpdateDateTime();
                row[10] = medicList.get(i).getCreateDateTime();
                model.addRow(row);
            }
        }
        else if(comboMedicine.getSelectedItem().equals("药水"))
        {
            GrassMedicinePotion medic = new GrassMedicinePotion();
            List<GrassMedicinePotion> medicList = new ArrayList<GrassMedicinePotion>();
            medicList = medic.getGrassMedicinePotion();
            DefaultTableModel model = (DefaultTableModel)tblMedicine.getModel();
            Object row[] = new Object[11];
            for(int i =0; i<medicList.size(); i++)
            {
                row[0] = medicList.get(i).getCode();
                row[1] = medicList.get(i).getName();
                row[2] = medicList.get(i).getComponent();
                row[3] = medicList.get(i).getIndications();
                row[4] = medicList.get(i).getEffect();
                row[5] = medicList.get(i).getScoop();
                row[6] = medicList.get(i).getGram();
                row[7] = medicList.get(i).getCost();
                row[8] = medicList.get(i).getSellprice();
                row[9] = medicList.get(i).getLastUpdateDateTime();
                row[10] = medicList.get(i).getCreateDateTime();
                model.addRow(row);
            }
        }
    }
    
    public void show_medical_ID(String ID) throws SQLException{
        
        if(comboMedicine.getSelectedItem().equals("单味药粉")) // traitional medicine potion
        {
            TraditionalMedicinePill medic = new TraditionalMedicinePill();
            List<TraditionalMedicinePill> medicList = new ArrayList<TraditionalMedicinePill>();
            medicList = medic.findTraditionalMedicinePillDetails("ID",ID);
            if(medic.validateAddTraditionalMedicinePill("ID", ID) == 0)
            {
                JOptionPane.showMessageDialog(rootPane, "ID错误或是药选项错误");
            }
            else
            {
                txtName.setText(medicList.get(0).getName());
                txtComponent.setText(medicList.get(0).getProperty());
                txtIndication.setText(medicList.get(0).getAppliance());
                txtEffect.setText(medicList.get(0).getEffect());
                txtScoop.setText(String.valueOf(medicList.get(0).getScoop()));
                txtWeight.setText(String.valueOf(medicList.get(0).getGram()));
                txtCost.setText(String.valueOf(medicList.get(0).getCost()));
                txtPrice.setText(String.valueOf(medicList.get(0).getSellprice()));
                disabledTextBox();
            }
            DefaultTableModel model = (DefaultTableModel)tblMedicine.getModel();
            Object row[] = new Object[11];
            for(int i =0; i<medicList.size(); i++)
            {
                row[0] = medicList.get(i).getCode();
                row[1] = medicList.get(i).getName();
                row[2] = medicList.get(i).getProperty();
                row[3] = medicList.get(i).getAppliance();
                row[4] = medicList.get(i).getEffect();
                row[5] = medicList.get(i).getScoop();
                row[6] = medicList.get(i).getGram();
                row[7] = medicList.get(i).getCost();
                row[8] = medicList.get(i).getSellprice();
                row[9] = medicList.get(i).getLastUpdateDateTime();
                row[10] = medicList.get(i).getCreateDateTime();
                model.addRow(row);
            }
        }
        else if(comboMedicine.getSelectedItem().equals("复方药粉"))
        {
            TraditionalMedicinePotion medic = new TraditionalMedicinePotion();
            List<TraditionalMedicinePotion> medicList = new ArrayList<TraditionalMedicinePotion>();
            medicList = medic.findTraditionalMedicinePotionDetails("ID",ID);
            if(medic.validateTraditionalMedicinePotion("ID", ID) == 0)
            {
                JOptionPane.showMessageDialog(rootPane, "ID错误或是药选项错误");
            }
            else
            {
                txtName.setText(medicList.get(0).getName());
                txtComponent.setText(medicList.get(0).getComponent());
                txtIndication.setText(medicList.get(0).getIndications());
                txtEffect.setText(medicList.get(0).getEffect());
                txtScoop.setText(String.valueOf(medicList.get(0).getScoop()));
                txtWeight.setText(String.valueOf(medicList.get(0).getGram()));
                txtCost.setText(String.valueOf(medicList.get(0).getCost()));
                txtPrice.setText(String.valueOf(medicList.get(0).getSellprice()));
                disabledTextBox();
            }
            DefaultTableModel model = (DefaultTableModel)tblMedicine.getModel();
            Object row[] = new Object[11];
            for(int i =0; i<medicList.size(); i++)
            {
                row[0] = medicList.get(i).getCode();
                row[1] = medicList.get(i).getName();
                row[2] = medicList.get(i).getComponent();
                row[3] = medicList.get(i).getIndications();
                row[4] = medicList.get(i).getEffect();
                row[5] = medicList.get(i).getScoop();
                row[6] = medicList.get(i).getGram();
                row[7] = medicList.get(i).getCost();
                row[8] = medicList.get(i).getSellprice();
                row[9] = medicList.get(i).getLastUpdateDateTime();
                row[10] = medicList.get(i).getCreateDateTime();
                model.addRow(row);
            }
        }
        else if(comboMedicine.getSelectedItem().equals("药丸"))
        {
            GrassMedicinePill medic = new GrassMedicinePill();
            List<GrassMedicinePill> medicList = new ArrayList<GrassMedicinePill>();
            medicList = medic.findGrassMedicinePillDetails("ID",ID);
            if(medic.validateGrassMedicinePill("ID", ID) == 0)
            {
                JOptionPane.showMessageDialog(rootPane, "ID错误或是药选项错误");
            }
            else
            {
                txtName.setText(medicList.get(0).getName());
                txtComponent.setText(medicList.get(0).getComponent());
                txtIndication.setText(medicList.get(0).getIndications());
                txtEffect.setText(medicList.get(0).getEffect());
                txtScoop.setText(String.valueOf(medicList.get(0).getScoop()));
                txtWeight.setText(String.valueOf(medicList.get(0).getGram()));
                txtCost.setText(String.valueOf(medicList.get(0).getCost()));
                txtPrice.setText(String.valueOf(medicList.get(0).getSellprice()));
                disabledTextBox();
            }
            DefaultTableModel model = (DefaultTableModel)tblMedicine.getModel();
            Object row[] = new Object[11];
            for(int i =0; i<medicList.size(); i++)
            {
                row[0] = medicList.get(i).getCode();
                row[1] = medicList.get(i).getName();
                row[2] = medicList.get(i).getComponent();
                row[3] = medicList.get(i).getIndications();
                row[4] = medicList.get(i).getEffect();
                row[5] = medicList.get(i).getScoop();
                row[6] = medicList.get(i).getGram();
                row[7] = medicList.get(i).getCost();
                row[8] = medicList.get(i).getSellprice();
                row[9] = medicList.get(i).getLastUpdateDateTime();
                row[10] = medicList.get(i).getCreateDateTime();
                model.addRow(row);
            }
        }
        else if(comboMedicine.getSelectedItem().equals("药水"))
        {
            GrassMedicinePotion medic = new GrassMedicinePotion();
            List<GrassMedicinePotion> medicList = new ArrayList<GrassMedicinePotion>();
            medicList = medic.findGrassMedicinePotionDetails("ID",ID);
            if(medic.validateAddGrassMedicinePotion("ID", ID) == 0)
            {
                JOptionPane.showMessageDialog(rootPane, "ID错误或是药选项错误");
            }
            else
            {
                txtName.setText(medicList.get(0).getName());
                txtComponent.setText(medicList.get(0).getComponent());
                txtIndication.setText(medicList.get(0).getIndications());
                txtEffect.setText(medicList.get(0).getEffect());
                txtScoop.setText(String.valueOf(medicList.get(0).getScoop()));
                txtWeight.setText(String.valueOf(medicList.get(0).getGram()));
                txtCost.setText(String.valueOf(medicList.get(0).getCost()));
                txtPrice.setText(String.valueOf(medicList.get(0).getSellprice()));
                disabledTextBox();
            }
            DefaultTableModel model = (DefaultTableModel)tblMedicine.getModel();
            Object row[] = new Object[11];
            for(int i =0; i<medicList.size(); i++)
            {
                row[0] = medicList.get(i).getCode();
                row[1] = medicList.get(i).getName();
                row[2] = medicList.get(i).getComponent();
                row[3] = medicList.get(i).getIndications();
                row[4] = medicList.get(i).getEffect();
                row[5] = medicList.get(i).getScoop();
                row[6] = medicList.get(i).getGram();
                row[7] = medicList.get(i).getCost();
                row[8] = medicList.get(i).getSellprice();
                row[9] = medicList.get(i).getLastUpdateDateTime();
                row[10] = medicList.get(i).getCreateDateTime();
                model.addRow(row);
            }
        }
    }

    public void disabledTextBox()
    {
        txtName.setEnabled(true);
        txtComponent.setEnabled(true);
        txtIndication.setEnabled(true);
        txtEffect.setEnabled(true);
        txtScoop.setEnabled(true);
        txtWeight.setEnabled(true);
        txtCost.setEnabled(true);
        txtPrice.setEnabled(true);
        txtID.setEnabled(false);
    }
    
    public void comboMedicine()
    {
        try {
            Code code = new Code();
            
            for(int i = 0; i < code.getComboMedicine().size(); i++)
            {
                System.out.println(code.getComboMedicine().get(i).toString());
                comboMedicine.addItem(code.getComboMedicine().get(i).getCode());
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "comboMedicine get error on line 886, "+ex.getMessage());
        }
    }
    
    public void changeLabel()
    {
        if(comboMedicine.getSelectedItem().equals("药丸"))
        {
            lblWeight.setText("'S");
            lblCost.setText("本钱 RM/'S: RM");
            lblPrice.setText("价格 RM/'S: RM");
        }
        else if(comboMedicine.getSelectedItem().equals("药水"))
        {
            lblWeight.setText("ML");
            lblCost.setText("本钱 RM/10 ML: RM");
            lblPrice.setText("价格 RM/10 ML: RM");
        }
        else
        {
            lblWeight.setText("GM");
            lblCost.setText("本钱 RM/GM: RM");
            lblPrice.setText("价格 RM/GM: RM");
        }
    }
    
    public void widthTable()
    {
        tblMedicine.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        //new JScrollPane(tblMedicine, JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        TableColumnModel columnModel = tblMedicine.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(100);
        columnModel.getColumn(1).setPreferredWidth(50);
        columnModel.getColumn(2).setPreferredWidth(200);
        columnModel.getColumn(3).setPreferredWidth(200);
        columnModel.getColumn(4).setPreferredWidth(100);
        columnModel.getColumn(5).setPreferredWidth(100);
        columnModel.getColumn(6).setPreferredWidth(70);
        columnModel.getColumn(7).setPreferredWidth(50);
        columnModel.getColumn(8).setPreferredWidth(50);
        columnModel.getColumn(9).setPreferredWidth(100);
        columnModel.getColumn(10).setPreferredWidth(100);
        
    }
    
    public void resetTextBox()
    {
        txtID.setText("");
        txtName.setText("");
        txtComponent.setText("");
        txtIndication.setText("");
        txtEffect.setText("");
        txtScoop.setText("");
        txtWeight.setText("");
        txtCost.setText("");
        txtPrice.setText("");
        txtID.setEnabled(true);
        txtName.setEnabled(false);
        txtComponent.setEnabled(false);
        txtIndication.setEnabled(false);
        txtEffect.setEnabled(false);
        txtScoop.setEnabled(false);
        txtWeight.setEnabled(false);
        txtCost.setEnabled(false);
        txtPrice.setEnabled(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyMedicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnModify;
    private javax.swing.JComboBox<String> comboMedicine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblCost;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JLabel lblzhucheng;
    private javax.swing.JLabel lblzhuzi;
    private javax.swing.JTable tblMedicine;
    private javax.swing.JTextArea txtComponent;
    private javax.swing.JTextField txtCost;
    private javax.swing.JTextField txtEffect;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextArea txtIndication;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtScoop;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
