/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medical;

import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Sheng
 */
public class MonthYear extends javax.swing.JFrame {

    /**
     * Creates new form MonthYear
     */
    private User user;
    public MonthYear(User user)
    {
        this.user = user;
        initComponents();
    }
    
    public MonthYear() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFromYear = new javax.swing.JTextField();
        txtToYear = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFromMonth = new javax.swing.JTextField();
        txtToMonth = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        jLabel1.setText("月份：");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(371, 42, 75, 34);

        jLabel2.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        jLabel2.setText("年份：");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(549, 39, 75, 40);

        txtFromYear.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        txtFromYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFromYearActionPerformed(evt);
            }
        });
        getContentPane().add(txtFromYear);
        txtFromYear.setBounds(540, 120, 86, 42);

        txtToYear.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        getContentPane().add(txtToYear);
        txtToYear.setBounds(540, 240, 86, 40);

        btnBack.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        btnBack.setText("退出");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(244, 374, 128, 45);

        btnFind.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        btnFind.setText("寻找");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        getContentPane().add(btnFind);
        btnFind.setBounds(592, 374, 119, 45);

        jLabel3.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        jLabel3.setText("从：");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(277, 122, 50, 34);

        jLabel4.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        jLabel4.setText("到：");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(277, 244, 50, 34);

        txtFromMonth.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        getContentPane().add(txtFromMonth);
        txtFromMonth.setBounds(360, 120, 90, 40);

        txtToMonth.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        getContentPane().add(txtToMonth);
        txtToMonth.setBounds(360, 240, 90, 40);

        setBounds(0, 0, 954, 537);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFromYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFromYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFromYearActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        try {
            String frommonth = txtFromMonth.getText();
            String tomonth = txtToMonth.getText();
            String fromyear = txtFromYear.getText();
            String toyear = txtToYear.getText();
            String to="";
            if(frommonth.equalsIgnoreCase("") || tomonth.equalsIgnoreCase(""))
            {
                JOptionPane.showMessageDialog(rootPane, "请填月份！");
            }
            else if(fromyear.equalsIgnoreCase("") || toyear.equalsIgnoreCase(""))
            {
                JOptionPane.showMessageDialog(rootPane, "请填年份！");
            }
            else if(tomonth.length() > 2 || tomonth.length() < 1 || frommonth.length() > 2 || frommonth.length() < 1)
            {
                JOptionPane.showMessageDialog(rootPane, "月份错误！");
            }
            else if(toyear.length() > 2 || toyear.length() < 1 || fromyear.length() > 2 || fromyear.length() < 1)
            {
                 JOptionPane.showMessageDialog(rootPane, "年份错误！");
            }
            else
            {
                if(tomonth.length() == 1)
                {
                    tomonth = "0"+tomonth;
                }
                if(frommonth.length() == 1)
                {
                    frommonth = "0"+frommonth;
                }
                
                String from=fromyear+"-"+frommonth+"-01";

                switch(Integer.parseInt(tomonth))
                {
                    case 1: case 3: case 5: case 7: case 8: case 10: case 12:
                        to = toyear+"-"+tomonth+"-31";
                        break;
                    case 2:
                        if(Integer.parseInt(toyear) % 4==0)
                        {
                            to = toyear+"-"+tomonth+"-29";
                        }
                        else
                        {
                            to = toyear+"-"+tomonth+"-28";
                        }
                        break;
                    case 4: case 6: case 9: case 11:
                        to = toyear+"-"+tomonth+"-30";
                        break;
                    default:
                        JOptionPane.showMessageDialog(rootPane, "日期错误");
                        break;
                }
                ViewPatientDetail monthly = new ViewPatientDetail(user,from, to);
                monthly.setVisible(true);
                this.dispose();
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        PatientDetailMenu menu = new PatientDetailMenu(user);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonthYear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonthYear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonthYear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonthYear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonthYear().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnFind;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtFromMonth;
    private javax.swing.JTextField txtFromYear;
    private javax.swing.JTextField txtToMonth;
    private javax.swing.JTextField txtToYear;
    // End of variables declaration//GEN-END:variables
}
