/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import javaClass.User;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Sheng
 */
public class panelModifyChuFang extends javax.swing.JPanel {

    /**
     * Creates new form panelModifyChuFang
     */
    
    /*private User user;
    DefaultTableModel model;
    public String price;
    public int updatedelete = 0;
    private String ID;
    private String IC;
    private String Name;
    private String Phone;
    private String PrescriptionID;
    private String Chufang;
    private String CategoryTable;
    private String NameTable;
    private String Jiliang;
    private String Price;
    private String TotalPrice;
    private String from;
    private String to;
    private String initialIC;
    private String initialID;
    private int option = 0;
    
    public panelModifyChuFang() {
        initComponents();
        createColumns();
    }

    public panelModifyChuFang(User user) throws SQLException {
        initComponents();
        this.user = user;
        comboBoxMedicine.setVisible(false);
        comboBoxName.setVisible(false);
        spinnerJiLiang.setVisible(false);
        txtMedicine.setEnabled(false);
        txtMedicineName.setEnabled(false);
        txtJiliang.setEnabled(false);
        txtChufang.setEnabled(false);
        txtPrice.setEnabled(false);
        txtTotalPrice.setEnabled(false);
        txtName.setEnabled(false);
        txtPhone.setEnabled(false);
        createColumns();
        FindByMedicineName2(String.valueOf(comboBoxName.getSelectedItem()));
        medicineCategory();
        txtPrice.setText("");
        show_table();
        widthTable();
        txtPrescriptionID.setVisible(false);
        JTableHeader tableHeader = tblChufang.getTableHeader();
        tableHeader.setFont(new Font("STXihei", Font.BOLD, 18));
        execute();
        jScrollPane1.getViewport().setBackground(Color.WHITE);
        ImageIcon iconLogo = new ImageIcon(getClass().getResource("/menu/hengsengtong.png"));
        lbllogo.setIcon(iconLogo);
    }
    
    public panelModifyChuFang(User user, String ID, String IC, String Name, String Phone, String PrescriptionID, String Chufang,
            String CategoryTable, String NameTable, String Jiliang, String Price, String TotalPrice, String from, String to,
            String initialIC, String initialID, int option) throws SQLException
    {
        this.user = user;
        this.ID = ID;
        this.IC = IC;
        this.Name = Name;
        this.Phone = Phone;
        this.PrescriptionID = PrescriptionID;
        this.Chufang = Chufang;
        this.CategoryTable = CategoryTable;
        this.NameTable = NameTable;
        this.Jiliang = Jiliang;
        this.Price = Price;
        this.TotalPrice = TotalPrice;
        this.from = from;
        this.to = to;
        this.initialIC = initialIC;
        this.initialID = initialID;
        this.option = option;
        createColumns();
        FindByMedicineName2(String.valueOf(comboBoxName.getSelectedItem()));
        medicineCategory();
        txtPrice.setText("");
        show_table();
        widthTable();
        txtPrescriptionID.setVisible(false);
        JTableHeader tableHeader = tblChufang.getTableHeader();
        tableHeader.setFont(new Font("STXihei", Font.BOLD, 18));
        btnReset.setVisible(false);
        execute();
        ImageIcon iconLogo = new ImageIcon(getClass().getResource("/menu/hengsengtong.png"));
        lbllogo.setIcon(iconLogo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPrescriptionID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChufang = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnFindIC = new javax.swing.JButton();
        txtIC = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        btnFindID = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtChufang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboBoxMedicine = new javax.swing.JComboBox<>();
        txtMedicine = new javax.swing.JTextField();
        txtMedicineName = new javax.swing.JTextField();
        comboBoxName = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        spinnerJiLiang = new javax.swing.JSpinner();
        txtJiliang = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTotalPrice = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnModifyMedicine = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        txtPrescriptionID.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        add(txtPrescriptionID);
        txtPrescriptionID.setBounds(60, 10, 230, 40);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tblChufang.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        tblChufang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblChufang.setFocusable(false);
        tblChufang.setGridColor(new java.awt.Color(255, 255, 255));
        tblChufang.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblChufang.setRowHeight(25);
        tblChufang.setShowVerticalLines(false);
        tblChufang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChufangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblChufang);

        add(jScrollPane1);
        jScrollPane1.setBounds(800, 20, 828, 768);

        jLabel2.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel2.setText("IC：");
        add(jLabel2);
        jLabel2.setBounds(100, 80, 60, 40);

        btnFindIC.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        btnFindIC.setText("寻找");
        btnFindIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindICActionPerformed(evt);
            }
        });
        add(btnFindIC);
        btnFindIC.setBounds(330, 130, 100, 40);

        txtIC.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        add(txtIC);
        txtIC.setBounds(150, 80, 280, 40);

        jLabel9.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel9.setText("ID:");
        add(jLabel9);
        jLabel9.setBounds(450, 80, 30, 40);

        txtID.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        add(txtID);
        txtID.setBounds(490, 80, 250, 40);

        btnFindID.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        btnFindID.setText("寻找");
        btnFindID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindIDActionPerformed(evt);
            }
        });
        add(btnFindID);
        btnFindID.setBounds(640, 130, 100, 40);

        txtName.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        add(txtName);
        txtName.setBounds(150, 180, 590, 40);

        txtPhone.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        add(txtPhone);
        txtPhone.setBounds(150, 250, 590, 40);

        jLabel11.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel11.setText("电话号码：");
        add(jLabel11);
        jLabel11.setBounds(50, 250, 95, 40);

        jLabel10.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel10.setText("姓名：");
        add(jLabel10);
        jLabel10.setBounds(70, 180, 70, 40);
        add(jSeparator1);
        jSeparator1.setBounds(30, 310, 730, 20);

        txtChufang.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        add(txtChufang);
        txtChufang.setBounds(160, 340, 590, 40);

        jLabel3.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel3.setText("处方：");
        add(jLabel3);
        jLabel3.setBounds(110, 340, 69, 40);

        jLabel4.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel4.setText("药物种类：");
        add(jLabel4);
        jLabel4.setBounds(70, 420, 110, 40);

        comboBoxMedicine.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        comboBoxMedicine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "复方药粉" }));
        comboBoxMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxMedicineActionPerformed(evt);
            }
        });
        add(comboBoxMedicine);
        comboBoxMedicine.setBounds(160, 420, 260, 40);

        txtMedicine.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        add(txtMedicine);
        txtMedicine.setBounds(160, 420, 590, 40);

        txtMedicineName.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        add(txtMedicineName);
        txtMedicineName.setBounds(160, 500, 590, 40);

        comboBoxName.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        comboBoxName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxNameActionPerformed(evt);
            }
        });
        add(comboBoxName);
        comboBoxName.setBounds(160, 500, 260, 40);

        jLabel5.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel5.setText("药物名称：");
        add(jLabel5);
        jLabel5.setBounds(70, 500, 100, 40);

        jLabel6.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel6.setText("剂量：");
        add(jLabel6);
        jLabel6.setBounds(100, 580, 69, 40);

        spinnerJiLiang.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        spinnerJiLiang.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerJiLiangStateChanged(evt);
            }
        });
        add(spinnerJiLiang);
        spinnerJiLiang.setBounds(160, 580, 80, 40);

        txtJiliang.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        add(txtJiliang);
        txtJiliang.setBounds(160, 580, 590, 40);

        jLabel7.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel7.setText("价格/G:");
        add(jLabel7);
        jLabel7.setBounds(70, 660, 70, 40);

        txtPrice.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        add(txtPrice);
        txtPrice.setBounds(160, 660, 590, 40);

        jLabel8.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel8.setText("总价值:");
        add(jLabel8);
        jLabel8.setBounds(80, 740, 63, 40);

        txtTotalPrice.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        add(txtTotalPrice);
        txtTotalPrice.setBounds(160, 740, 590, 40);

        btnBack.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        btnBack.setText("退出");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(120, 800, 100, 40);

        btnReset.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        btnReset.setText("重启");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        add(btnReset);
        btnReset.setBounds(240, 800, 100, 40);

        btnModifyMedicine.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        btnModifyMedicine.setText("更改");
        btnModifyMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyMedicineActionPerformed(evt);
            }
        });
        add(btnModifyMedicine);
        btnModifyMedicine.setBounds(360, 800, 100, 40);

        btnDelete.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        btnDelete.setText("删除");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete);
        btnDelete.setBounds(520, 800, 100, 40);

        btnModify.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        btnModify.setText("更新");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });
        add(btnModify);
        btnModify.setBounds(640, 800, 100, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void tblChufangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChufangMouseClicked
        // TODO add your handling code here:
//        txtMedicine.setEnabled(false);
//        txtMedicineName.setEnabled(false);
//        txtJiliang.setEnabled(false);
//        txtMedicine.setVisible(true);
//        txtMedicineName.setVisible(true);
//        txtJiliang.setVisible(true);
//        comboBoxMedicine.setVisible(false);
//        comboBoxName.setVisible(false);
//        spinnerJiLiang.setVisible(false);
//        txtID.setEnabled(true);
//        txtIC.setEnabled(true);
//        int index = tblChufang.getSelectedRow();
//        TableModel model = tblChufang.getModel();
//        String ID = model.getValueAt(index, 0).toString();
//        String IC = model.getValueAt(index,1).toString();
//        String Name = model.getValueAt(index,2).toString();
//        String Phone = model.getValueAt(index,3).toString();
//        String Chufang = model.getValueAt(index,4).toString();
//        String medicine = model.getValueAt(index,5).toString();
//        String medicineName = model.getValueAt(index,6).toString();
//        String Jiliang = model.getValueAt(index,7).toString();
//        String price = model.getValueAt(index,8).toString();
//        String totalprice = model.getValueAt(index,9).toString();
//        String prescriptionID = model.getValueAt(index, 22).toString();
//
//        txtID.setText(ID);
//        txtIC.setText(IC);
//        txtName.setText(Name);
//        txtPhone.setText(Phone);
//        txtChufang.setText(Chufang);
//        txtMedicine.setText(medicine);
//        txtMedicineName.setText(medicineName);
//        txtJiliang.setText(Jiliang);
//        txtPrice.setText(price);
//        txtTotalPrice.setText(totalprice);
//        txtPrescriptionID.setText(prescriptionID);
//        updatedelete = 0;

        //disabledTextBox();
    }//GEN-LAST:event_tblChufangMouseClicked

    private void btnFindICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindICActionPerformed
        // TODO add your handling code here:
//        Find();
    }//GEN-LAST:event_btnFindICActionPerformed

    private void btnFindIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindIDActionPerformed
        // TODO add your handling code here:
//        Find();
    }//GEN-LAST:event_btnFindIDActionPerformed

    private void comboBoxMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxMedicineActionPerformed
        // TODO add your handling code here:
//        try {
//            // TODO add your handling code here:
//            String name = comboBoxMedicine.getSelectedItem().toString();
//
//            medicineName(name);
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(rootPane, "NewPatientDisease.comboBoxMedicineActionPerformed get error on line 609,"+ex.getMessage());
//        }
    }//GEN-LAST:event_comboBoxMedicineActionPerformed

    private void comboBoxNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxNameActionPerformed
        // TODO add your handling code here:
//        FindByMedicineName2(String.valueOf(comboBoxName.getSelectedItem()));
    }//GEN-LAST:event_comboBoxNameActionPerformed

    private void spinnerJiLiangStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerJiLiangStateChanged
        // TODO add your handling code here:
        String jiliang = spinnerJiLiang.getValue().toString();
        float jiliang1 = Float.valueOf(jiliang);
        float totalprice = Float.valueOf(txtPrice.getText());
        float total = jiliang1 * totalprice;

        txtTotalPrice.setText(String.valueOf(total));
    }//GEN-LAST:event_spinnerJiLiangStateChanged

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
//        if(option == 5)
//        {
//            try {
//                ViewDiseaseDetail disease = new ViewDiseaseDetail(user,from,to,initialIC,initialID);
//                disease.setVisible(true);
//                this.dispose();
//            } catch (SQLException ex) {
//                ex.printStackTrace();
//            }
//        }
//        else
//        {
//            DiseaseMenu disease = new DiseaseMenu(user);
//            disease.setVisible(true);
//            this.dispose();
//        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
//        txtMedicine.setEnabled(false);
//        txtMedicineName.setEnabled(false);
//        txtJiliang.setEnabled(false);
//        txtMedicine.setVisible(true);
//        txtMedicineName.setVisible(true);
//        txtJiliang.setVisible(true);
//        comboBoxMedicine.setVisible(false);
//        comboBoxName.setVisible(false);
//        spinnerJiLiang.setVisible(false);
//        txtPrescriptionID.setText("");
//        txtID.setText("");
//        txtIC.setText("");
//        txtName.setText("");
//        txtPhone.setText("");
//        txtChufang.setText("");
//        txtMedicine.setText("");
//        txtMedicineName.setText("");
//        txtJiliang.setText("");
//        price = txtPrice.getText();
//
//        txtPrice.setText("");
//        txtTotalPrice.setText("");
//        updatedelete = 0;
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnModifyMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyMedicineActionPerformed
        // TODO add your handling code here:
//        txtMedicine.setVisible(false);
//        comboBoxMedicine.setVisible(true);
//        txtMedicineName.setVisible(false);
//        comboBoxName.setVisible(true);
//        txtJiliang.setVisible(false);
//        spinnerJiLiang.setVisible(true);
//        txtTotalPrice.setText("0.00");
//        spinnerJiLiang.setValue(0);
//        FindByMedicineName2(String.valueOf(comboBoxName.getSelectedItem()));
//        updatedelete = 1;
    }//GEN-LAST:event_btnModifyMedicineActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
//        delete();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        // TODO add your handling code here:
//        if(updatedelete == 1)
//        {
//            update();
//        }
//        else
//        {
//            JOptionPane.showMessageDialog(rootPane, "你没有更改资料!");
//        }
    }//GEN-LAST:event_btnModifyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFindIC;
    private javax.swing.JButton btnFindID;
    private javax.swing.JButton btnModify;
    private javax.swing.JButton btnModifyMedicine;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> comboBoxMedicine;
    private javax.swing.JComboBox<String> comboBoxName;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner spinnerJiLiang;
    private javax.swing.JTable tblChufang;
    private javax.swing.JTextField txtChufang;
    private javax.swing.JTextField txtIC;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtJiliang;
    private javax.swing.JTextField txtMedicine;
    private javax.swing.JTextField txtMedicineName;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPrescriptionID;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtTotalPrice;
    // End of variables declaration//GEN-END:variables
}
