/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.sql.SQLException;
import javaClass.Code;
import javaClass.Disease;
import javaClass.GrassMedicinePill;
import javaClass.GrassMedicinePotion;
import javaClass.Patient;
import javaClass.TraditionalMedicinePill;
import javaClass.TraditionalMedicinePotion;
import javaClass.User;
import javax.swing.JOptionPane;

/**
 *
 * @author Sheng
 */
public class ChangePassword extends javax.swing.JFrame {

    /**
     * Creates new form ChangePassword
     */
    private User user;
    
    public ChangePassword() {
        initComponents();
    }

    public ChangePassword(User user)
    {
        this.user = user;
        initComponents();
        lblName.setText(user.getUserid());
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        lbllogo = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        findHeader = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        panelBody = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNewID = new javax.swing.JTextField();
        txtConfirmID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtOldID = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        txtConfirmPassword = new javax.swing.JPasswordField();
        txtNewPassword = new javax.swing.JPasswordField();
        txtOldPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelHeader.setBackground(new java.awt.Color(255, 204, 204));
        panelHeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        panelHeader.setForeground(new java.awt.Color(153, 153, 153));
        panelHeader.setLayout(null);
        panelHeader.add(lbllogo);
        lbllogo.setBounds(14, 2, 231, 70);

        jLabel20.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        jLabel20.setText("登入：");
        panelHeader.add(jLabel20);
        jLabel20.setBounds(1670, 5, 75, 60);

        lblName.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        panelHeader.add(lblName);
        lblName.setBounds(1752, 5, 127, 60);

        findHeader.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        findHeader.setText("更改密码");
        panelHeader.add(findHeader);
        findHeader.setBounds(960, 0, 200, 70);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("CopyRight © Heng Seng Tong");
        jPanel1.add(jLabel21);

        panelBody.setBackground(new java.awt.Color(255, 255, 255));
        panelBody.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        panelBody.setLayout(null);

        jLabel1.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel1.setText("旧账号:");
        panelBody.add(jLabel1);
        jLabel1.setBounds(400, 100, 80, 40);

        jLabel3.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel3.setText("新账号:");
        panelBody.add(jLabel3);
        jLabel3.setBounds(400, 200, 63, 40);

        txtNewID.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        panelBody.add(txtNewID);
        txtNewID.setBounds(490, 200, 600, 40);

        txtConfirmID.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        txtConfirmID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfirmIDActionPerformed(evt);
            }
        });
        panelBody.add(txtConfirmID);
        txtConfirmID.setBounds(490, 300, 600, 40);

        jLabel2.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel2.setText("确认新账号:");
        panelBody.add(jLabel2);
        jLabel2.setBounds(360, 300, 120, 40);

        jLabel5.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel5.setText("旧密码:");
        panelBody.add(jLabel5);
        jLabel5.setBounds(390, 390, 63, 40);

        jLabel6.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel6.setText("新密码:");
        panelBody.add(jLabel6);
        jLabel6.setBounds(390, 480, 80, 40);

        jLabel7.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel7.setText("确认密码：");
        panelBody.add(jLabel7);
        jLabel7.setBounds(370, 570, 95, 40);

        txtOldID.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        panelBody.add(txtOldID);
        txtOldID.setBounds(490, 100, 600, 40);

        btnBack.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        btnBack.setText("退出");
        btnBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        panelBody.add(btnBack);
        btnBack.setBounds(240, 640, 130, 50);

        btnFind.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        btnFind.setText("更改");
        btnFind.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        panelBody.add(btnFind);
        btnFind.setBounds(1110, 640, 130, 50);

        txtConfirmPassword.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        panelBody.add(txtConfirmPassword);
        txtConfirmPassword.setBounds(490, 570, 600, 40);

        txtNewPassword.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        panelBody.add(txtNewPassword);
        txtNewPassword.setBounds(490, 480, 600, 40);

        txtOldPassword.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        panelBody.add(txtOldPassword);
        txtOldPassword.setBounds(490, 390, 600, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(348, 348, 348)
                .addComponent(panelBody, javax.swing.GroupLayout.PREFERRED_SIZE, 1338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 1940, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1940, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(panelBody, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(870, 870, 870)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtConfirmIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmIDActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        SettingsMenu menu = new SettingsMenu(user);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        try {
            // TODO add your handling code here:
            Find();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnFindActionPerformed

    public void Find() throws SQLException
    {
        String oldID = txtOldID.getText();
        String newID = txtNewID.getText();
        String confirmID = txtConfirmID.getText();
        String oldPassword = txtOldPassword.getText();
        String newPassword = txtNewPassword.getText();
        String confirmPassword = txtConfirmPassword.getText();
        
        if(newID.equalsIgnoreCase(confirmID))
        {
            if(oldID.equalsIgnoreCase("") && newID.equalsIgnoreCase("") && confirmID.equalsIgnoreCase(""))
            {
                UpdatePassword(newPassword, confirmPassword, oldPassword,user.getUserid());
            }
            else if(oldID.equalsIgnoreCase(user.getUserid()))
            {
                User user = new User();
                Code code = new Code();
                Disease disease = new Disease();
                GrassMedicinePill  medicinepill = new GrassMedicinePill();
                GrassMedicinePotion medicinepotion = new GrassMedicinePotion();
                Patient  patient = new Patient();
                TraditionalMedicinePill traditionalpill = new TraditionalMedicinePill();
                TraditionalMedicinePotion traditionalpotion = new TraditionalMedicinePotion();
                String resultDisease = disease.UpdateUser(oldID, newID);
                String resultCode = code.UpdateUser(oldID, newID);
                String resultmedicinepill = medicinepill.UpdateUser(oldID, newID);
                String resultmedicinepotion = medicinepotion.UpdateUser(oldID, newID);
                String resultpatient = patient.UpdateUser(oldID, newID);
                String resulttraditionalpill = traditionalpill.UpdateUser(oldID, newID);
                String resulttraditionalpotion = traditionalpotion.UpdateUser(oldID, newID);
                String resultUser = user.UpdateUsername(oldID, newID);
                
                if(!oldID.equalsIgnoreCase("") && !newID.equalsIgnoreCase("") && !confirmID.equalsIgnoreCase(""))
                {
                    if(resultDisease != null && resultDisease.equalsIgnoreCase("1"))
                    {
                        if(resultmedicinepill != null && resultmedicinepill.equalsIgnoreCase("1"))
                        {
                            if(resultmedicinepotion != null && resultmedicinepotion.equalsIgnoreCase("1"))
                            {
                                if(resultpatient != null && resultpatient.equalsIgnoreCase("1"))
                                {
                                    if(resulttraditionalpill != null && resulttraditionalpill.equalsIgnoreCase("1"))
                                    {
                                        if(resulttraditionalpotion != null && resulttraditionalpotion.equalsIgnoreCase("1"))
                                        {
                                            if(resultCode != null && resultCode.equalsIgnoreCase("1"))
                                            {
                                                if(resultUser != null && resultUser.equalsIgnoreCase("1"))
                                                {
                                                    JOptionPane.showMessageDialog(rootPane, "ID 更改！");
                                                    lblName.setText(user.getUserid());
                                                    this.user = user;
                                                    UpdatePassword(newPassword, confirmPassword, oldPassword,newID);
                                                }
                                                else
                                                {
                                                    JOptionPane.showMessageDialog(rootPane, "ID不能更改！");
                                                    disease.UpdateUser(oldID, user.getUserid());
                                                    medicinepill.UpdateUser(oldID, user.getUserid());
                                                    medicinepotion.UpdateUser(oldID, user.getUserid());
                                                    patient.UpdateUser(oldID, user.getUserid());
                                                    traditionalpill.UpdateUser(oldID, user.getUserid());
                                                    traditionalpotion.UpdateUser(oldID, user.getUserid());
                                                    user.UpdateUsername(oldID, user.getUserid());
                                                }
                                            }
                                            else
                                            {
                                                JOptionPane.showMessageDialog(rootPane, "系统 ID 在 database不能更改！");
                                                disease.UpdateUser(oldID, user.getUserid());
                                                medicinepill.UpdateUser(oldID, user.getUserid());
                                                medicinepotion.UpdateUser(oldID, user.getUserid());
                                                patient.UpdateUser(oldID, user.getUserid());
                                                traditionalpill.UpdateUser(oldID, user.getUserid());
                                                traditionalpotion.UpdateUser(oldID, user.getUserid());
                                            }
                                        }
                                        else
                                        {
                                            JOptionPane.showMessageDialog(rootPane, "复方药粉 ID 在 database不能更改！");
                                            disease.UpdateUser(oldID, user.getUserid());
                                            medicinepill.UpdateUser(oldID, user.getUserid());
                                            medicinepotion.UpdateUser(oldID, user.getUserid());
                                            patient.UpdateUser(oldID, user.getUserid());
                                            traditionalpill.UpdateUser(oldID, user.getUserid());
                                        }
                                    }
                                    else
                                    {
                                        JOptionPane.showMessageDialog(rootPane, "单味药粉 ID 在 database不能更改！");
                                        disease.UpdateUser(oldID, user.getUserid());
                                        medicinepill.UpdateUser(oldID, user.getUserid());
                                        medicinepotion.UpdateUser(oldID, user.getUserid());
                                        patient.UpdateUser(oldID, user.getUserid());
                                    }
                                }
                                else
                                {
                                    JOptionPane.showMessageDialog(rootPane, "病人database不能更改！");
                                    disease.UpdateUser(oldID, user.getUserid());
                                    medicinepill.UpdateUser(oldID, user.getUserid());
                                    medicinepotion.UpdateUser(oldID, user.getUserid());
                                }
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(rootPane, "药丸 ID 在 database不能更改！");
                                disease.UpdateUser(oldID, user.getUserid());
                                medicinepill.UpdateUser(oldID, user.getUserid());
                            }
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(rootPane, "药丸 ID 在 database不能更改！");
                            disease.UpdateUser(oldID, user.getUserid());
                        }
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(rootPane, "病症 ID 在 database不能更改！");
                    }
                }
                else if(oldID.equalsIgnoreCase("") && newID.equalsIgnoreCase("") && confirmID.equalsIgnoreCase(""))
                {
                    UpdatePassword(newPassword, confirmPassword, oldPassword,user.getUserid());
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "ID 资料没填");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "原本的ID不一致！");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "ID不一致！");
        }
        
    }
    
    public void UpdatePassword(String newPassword, String confirmPassword, String oldPassword, String userid) throws SQLException
    {
        if(newPassword.equalsIgnoreCase(confirmPassword))
        {
            if(oldPassword.equalsIgnoreCase(user.getPassword()))
            {
                String resultUser = user.UpdatePassword(userid,newPassword);
                if(resultUser != null && resultUser.equalsIgnoreCase("1"))
                {
                    JOptionPane.showMessageDialog(rootPane, "更新密码成功！");
                }
                else
                {
                     JOptionPane.showMessageDialog(rootPane, "更新密码失败！");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "原本的密码不一致！");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "密码不一致！");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnFind;
    private javax.swing.JLabel findHeader;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JTextField txtConfirmID;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextField txtNewID;
    private javax.swing.JPasswordField txtNewPassword;
    private javax.swing.JTextField txtOldID;
    private javax.swing.JPasswordField txtOldPassword;
    // End of variables declaration//GEN-END:variables
}
