/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javaClass.Code;
import javaClass.Reference;
import javaClass.User;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Sheng
 */
public class ModifyDatabase extends javax.swing.JFrame {

    /**
     * Creates new form ModifyDatabase
     */
    private User user;
    private String userid = "";
    User users = new User();
    List<User> userList = new ArrayList<User>();
    DefaultTableModel model;
    DefaultTableModel model1;
    DefaultTableModel model2;
    Code code = new Code();
    List<Code> codeList = new ArrayList<Code>();
    Reference reference = new Reference();
    List<Reference> referenceList = new ArrayList<Reference>();
    
    public ModifyDatabase() {
        initComponents();
    }
    
    public ModifyDatabase(User user) {
        this.user = user;
        initComponents();
        userid = user.getUserid();
        lblName.setText(userid);
        userid = user.getUserid();
        tblMaintcodes.setVisible(false);
        tblUsers.setVisible(false);
        tblReference.setVisible(false);
        jScrollPaneMaintcodes.setVisible(false);
        jScrollPaneUsers.setVisible(false);
        jScrollPaneReference.setVisible(false);
        image();
        widthTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        lbllogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInsertDatabase = new javax.swing.JTextArea();
        jScrollPaneReference = new javax.swing.JScrollPane();
        tblReference = new javax.swing.JTable();
        jScrollPaneMaintcodes = new javax.swing.JScrollPane();
        tblMaintcodes = new javax.swing.JTable();
        jScrollPaneUsers = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtSelectTable = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        panelHeader.setBackground(new java.awt.Color(255, 204, 204));
        panelHeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        panelHeader.setForeground(new java.awt.Color(153, 153, 153));
        panelHeader.setLayout(null);
        panelHeader.add(lbllogo);
        lbllogo.setBounds(0, 0, 231, 70);

        jLabel1.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        jLabel1.setText("更改Database");
        panelHeader.add(jLabel1);
        jLabel1.setBounds(500, 0, 290, 70);

        jLabel13.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        jLabel13.setText("登入：");
        panelHeader.add(jLabel13);
        jLabel13.setBounds(1110, 0, 100, 70);

        lblName.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        panelHeader.add(lblName);
        lblName.setBounds(1210, 0, 160, 70);

        getContentPane().add(panelHeader);
        panelHeader.setBounds(0, 0, 1370, 70);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel2.setText("Table Name: (Select)");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 130, 210, 40);

        btnBack.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        btnBack.setText("退出");
        btnBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack);
        btnBack.setBounds(130, 450, 130, 50);

        btnInsert.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        btnInsert.setText("输入");
        btnInsert.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        jPanel2.add(btnInsert);
        btnInsert.setBounds(920, 450, 130, 50);

        txtInsertDatabase.setColumns(20);
        txtInsertDatabase.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        txtInsertDatabase.setRows(5);
        jScrollPane1.setViewportView(txtInsertDatabase);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(230, 10, 820, 90);

        tblReference.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        tblReference.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reference"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblReference.setRowHeight(25);
        jScrollPaneReference.setViewportView(tblReference);

        jPanel2.add(jScrollPaneReference);
        jScrollPaneReference.setBounds(80, 200, 970, 240);

        tblMaintcodes.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        tblMaintcodes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Number", "Remark", "User"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMaintcodes.setRowHeight(25);
        jScrollPaneMaintcodes.setViewportView(tblMaintcodes);

        jPanel2.add(jScrollPaneMaintcodes);
        jScrollPaneMaintcodes.setBounds(80, 200, 970, 240);

        tblUsers.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Userid", "password", "position"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUsers.setRowHeight(25);
        jScrollPaneUsers.setViewportView(tblUsers);

        jPanel2.add(jScrollPaneUsers);
        jScrollPaneUsers.setBounds(80, 200, 970, 240);

        jLabel3.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel3.setText("更改Database:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 10, 160, 40);

        txtSelectTable.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jPanel2.add(txtSelectTable);
        txtSelectTable.setBounds(230, 130, 820, 50);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(140, 90, 1150, 520);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("CopyRight © Heng Seng Tong");
        jPanel6.add(jLabel14);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(0, 650, 1370, 50);

        setBounds(0, 0, 1387, 744);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        try {
            // TODO add your handling code here:
            SettingsMenu settings = new SettingsMenu(user);
            settings.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        try {
            Insert();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnInsertActionPerformed

    public void Insert() throws SQLException
    {
        String query = txtInsertDatabase.getText();
        String table = txtSelectTable.getText();
        String firstLetter = query.substring(0, 1);
        
        if(firstLetter.equalsIgnoreCase("U") || firstLetter.equalsIgnoreCase("I") || firstLetter.equalsIgnoreCase("D") || firstLetter.equalsIgnoreCase("C") || firstLetter.equalsIgnoreCase("A"))
        {
            if(code.insertCode(query, userid).equalsIgnoreCase("1"))
            {
                JOptionPane.showMessageDialog(rootPane, "输入/更改成功！");
                txtInsertDatabase.setText("");
                jScrollPaneMaintcodes.setVisible(false);
                jScrollPaneUsers.setVisible(false);
                jScrollPaneReference.setVisible(false);
                tblMaintcodes.setVisible(false);
                tblUsers.setVisible(false);
                tblReference.setVisible(false);
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "输入/更改失败！");
                jScrollPaneMaintcodes.setVisible(false);
                jScrollPaneUsers.setVisible(false);
                jScrollPaneReference.setVisible(false);
                tblMaintcodes.setVisible(false);
                tblUsers.setVisible(false);
                tblReference.setVisible(false);
            }
        }
        else if(firstLetter.equalsIgnoreCase("S"))
        {
            if(table.equalsIgnoreCase("user"))
            {
                userList = users.getUsers();
                model = (DefaultTableModel)tblUsers.getModel();
                Object row[] = new Object[3];
                for(int i =0; i<userList.size(); i++)
                {
                    row[0] = userList.get(i).getUserid();
                    row[1] = userList.get(i).getPassword();
                    row[2] = userList.get(i).getPosition();
                    model.addRow(row);
                }
                jScrollPaneUsers.setVisible(true);
                jScrollPaneMaintcodes.setVisible(false);
                jScrollPaneReference.setVisible(false);
                tblMaintcodes.setVisible(false);
                tblUsers.setVisible(true);
                tblReference.setVisible(false);
            }
            else if(table.equalsIgnoreCase("Maintcode"))
            {
                codeList = code.getCodes();
                model1 = (DefaultTableModel)tblMaintcodes.getModel();
                Object row[] = new Object[4];
                for(int i =0; i<codeList.size(); i++)
                {
                    row[0] = codeList.get(i).getCode();
                    row[1] = codeList.get(i).getNumber();
                    row[2] = codeList.get(i).getRemark();
                    row[3] = codeList.get(i).getUser();
                    model1.addRow(row);
                }
                jScrollPaneUsers.setVisible(false);
                jScrollPaneMaintcodes.setVisible(true);
                jScrollPaneReference.setVisible(false);
                tblMaintcodes.setVisible(true);
                tblUsers.setVisible(false);
                tblReference.setVisible(false);
            }
            else if(table.equalsIgnoreCase("Reference"))
            {
                referenceList = reference.getReferences();
                model2 = (DefaultTableModel)tblReference.getModel();
                Object row[] = new Object[1];
                for(int i =0; i<referenceList.size(); i++)
                {
                    row[0] = referenceList.get(i).getReference();
                    model2.addRow(row);
                }
                jScrollPaneUsers.setVisible(false);
                jScrollPaneMaintcodes.setVisible(false);
                jScrollPaneReference.setVisible(true);
                tblMaintcodes.setVisible(false);
                tblUsers.setVisible(false);
                tblReference.setVisible(true);
            }
        }
    }
    
    public void image()
    {
        jScrollPaneUsers.getViewport().setBackground(Color.WHITE);
        jScrollPaneReference.getViewport().setBackground(Color.WHITE);
        jScrollPaneMaintcodes.getViewport().setBackground(Color.WHITE);
        ImageIcon iconLogo = new ImageIcon(getClass().getResource("/menu/hengsengtong.png"));
        lbllogo.setIcon(iconLogo);
        ImageIcon iconBack = new ImageIcon(getClass().getResource("/menu/smallBack.png"));
        btnBack.setIcon(iconBack);
        ImageIcon iconInsert = new ImageIcon(getClass().getResource("/menu/insertSmall.png"));
        btnInsert.setIcon(iconInsert);
        ImageIcon iconDatabase = new ImageIcon(getClass().getResource("/menu/databaseSettingsHeadMedium.png"));
        jLabel1.setIcon(iconDatabase);
    }
    
    public void widthTable()
    {
        jScrollPane1.getViewport().setBackground(Color.WHITE);
        JTableHeader tableHeader = tblUsers.getTableHeader();
        JTableHeader tableHeader1 = tblMaintcodes.getTableHeader();
        JTableHeader tableHeader2 = tblReference.getTableHeader();
        tableHeader.setFont(new Font("STXihei", Font.BOLD, 18));
        tableHeader1.setFont(new Font("STXihei", Font.BOLD, 18));
        tableHeader2.setFont(new Font("STXihei", Font.BOLD, 18));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyDatabase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnInsert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneMaintcodes;
    private javax.swing.JScrollPane jScrollPaneReference;
    private javax.swing.JScrollPane jScrollPaneUsers;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JTable tblMaintcodes;
    private javax.swing.JTable tblReference;
    private javax.swing.JTable tblUsers;
    private javax.swing.JTextArea txtInsertDatabase;
    private javax.swing.JTextField txtSelectTable;
    // End of variables declaration//GEN-END:variables
}
