/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.Color;
import javaClass.Excel;
import javaClass.User;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Sheng
 */
public class MonthYearIC extends javax.swing.JFrame {

    /**
     * Creates new form MonthYear
     */
    private User user;
    private int option;
    public MonthYearIC(User user, int option) {
        this.user = user;
        this.option = option;
        initComponents();
        image();
    }

    public MonthYearIC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        lbllogo = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        headerFind = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        panelBody = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIC = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtToMonth = new javax.swing.JTextField();
        txtToYear = new javax.swing.JTextField();
        txtFromYear = new javax.swing.JTextField();
        txtFromMonth = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        panelHeader.setBackground(new java.awt.Color(255, 204, 204));
        panelHeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        panelHeader.setForeground(new java.awt.Color(153, 153, 153));
        panelHeader.setLayout(null);
        panelHeader.add(lbllogo);
        lbllogo.setBounds(14, 2, 231, 70);

        jLabel17.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        jLabel17.setText("登入：");
        panelHeader.add(jLabel17);
        jLabel17.setBounds(1651, 2, 75, 70);

        lblName.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        panelHeader.add(lblName);
        lblName.setBounds(1720, 0, 160, 70);

        headerFind.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        headerFind.setText("寻找");
        panelHeader.add(headerFind);
        headerFind.setBounds(890, 0, 260, 70);

        jPanel2.add(panelHeader);
        panelHeader.setBounds(0, 0, 1940, 70);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("CopyRight © Heng Seng Tong");
        jPanel1.add(jLabel18);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(0, 940, 1940, 50);

        panelBody.setBackground(new java.awt.Color(255, 255, 255));
        panelBody.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        panelBody.setLayout(null);

        jLabel6.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        jLabel6.setText("ID:");
        panelBody.add(jLabel6);
        jLabel6.setBounds(380, 540, 50, 40);

        jLabel5.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        jLabel5.setText("IC:");
        panelBody.add(jLabel5);
        jLabel5.setBounds(380, 420, 50, 40);

        txtIC.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        panelBody.add(txtIC);
        txtIC.setBounds(470, 420, 270, 40);

        jLabel4.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        jLabel4.setText("到：");
        panelBody.add(jLabel4);
        jLabel4.setBounds(390, 300, 50, 34);

        txtToMonth.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        panelBody.add(txtToMonth);
        txtToMonth.setBounds(470, 300, 90, 40);

        txtToYear.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        panelBody.add(txtToYear);
        txtToYear.setBounds(650, 300, 86, 40);

        txtFromYear.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        txtFromYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFromYearActionPerformed(evt);
            }
        });
        panelBody.add(txtFromYear);
        txtFromYear.setBounds(650, 180, 86, 42);

        txtFromMonth.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        panelBody.add(txtFromMonth);
        txtFromMonth.setBounds(470, 180, 90, 40);

        jLabel3.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        jLabel3.setText("从：");
        panelBody.add(jLabel3);
        jLabel3.setBounds(390, 180, 50, 34);

        jLabel2.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        jLabel2.setText("年份：");
        panelBody.add(jLabel2);
        jLabel2.setBounds(650, 70, 75, 40);

        jLabel1.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        jLabel1.setText("月份：");
        panelBody.add(jLabel1);
        jLabel1.setBounds(470, 70, 75, 40);

        txtID.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        panelBody.add(txtID);
        txtID.setBounds(470, 540, 270, 40);

        btnBack.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        btnBack.setText("退出");
        btnBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        panelBody.add(btnBack);
        btnBack.setBounds(380, 680, 170, 70);

        btnFind.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        btnFind.setText("寻找");
        btnFind.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        panelBody.add(btnFind);
        btnFind.setBounds(750, 680, 170, 70);

        jPanel2.add(panelBody);
        panelBody.setBounds(370, 90, 1200, 820);

        jScrollPane1.setViewportView(jPanel2);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 1940, 990);

        setBounds(0, 0, 1957, 1037);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFromYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFromYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFromYearActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        String frommonth = txtFromMonth.getText();
        String tomonth = txtToMonth.getText();
        String fromyear = txtFromYear.getText();
        String toyear = txtToYear.getText();
        String IC = txtIC.getText();
        String ID = txtID.getText();
        System.out.println(option);
        Excel monthyear = new Excel();
        HashMap<String,String> monthyearIC = new HashMap<String,String>();
        monthyearIC = monthyear.checkMonthYearIC(frommonth, tomonth, fromyear, toyear, IC, ID);
        if(!monthyearIC.get("Messages").equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(rootPane, monthyearIC.get("Messages"));
        }
        else
        {
            try {
                if(option == 2)
                {
                    viewpatientpage(monthyearIC.get("From"), monthyearIC.get("To"), monthyearIC.get("IC"), monthyearIC.get("ID"));
                }
                else if(option == 5)
                {
                    viewdiseasedetail(monthyearIC.get("From"), monthyearIC.get("To"), monthyearIC.get("IC"), monthyearIC.get("ID"));
                }
                else
                {
                    monthlypatientreport(monthyearIC.get("From"), monthyearIC.get("To"), monthyearIC.get("IC"), monthyearIC.get("ID"));
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "MonthYearIC.btnFindActionPerformed get error on line 162, "+monthyearIC.get("Messages"));
            }
        }
    }//GEN-LAST:event_btnFindActionPerformed

    public void viewpatientpage(String from, String to, String IC, String ID) throws SQLException { //option = 2
        ViewPatientDetail monthly = new ViewPatientDetail(user, from, to, IC, ID);
        monthly.setVisible(true);
        this.dispose();
    }

    public void monthlypatientreport(String from, String to, String IC, String ID)throws SQLException { // option =3
       MonthlyPatientDiseaseReport monthly = new MonthlyPatientDiseaseReport(user, from, to, IC, ID);
       monthly.setVisible(true);
       this.dispose();
    }
    
    public void viewdiseasedetail(String from, String to, String IC, String ID)throws SQLException { // option =5
        ViewDiseaseDetail disease = new ViewDiseaseDetail(user, from, to, IC, ID);
        disease.setVisible(true);
        this.dispose();
    }
    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        if(option == 5)
        {
            DiseaseMenu menu = new DiseaseMenu(user);
            menu.setVisible(true);
            this.dispose();
        }
        else
        {
            PatientDetailMenu menu = new PatientDetailMenu(user);
            menu.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnBackActionPerformed

    public void image()
    {
        ImageIcon iconLogo = new ImageIcon(getClass().getResource("/menu/hengsengtong.png"));
        lbllogo.setIcon(iconLogo);
        ImageIcon iconBack = new ImageIcon(getClass().getResource("/menu/smallBack.png"));
        btnBack.setIcon(iconBack);
        ImageIcon iconFind = new ImageIcon(getClass().getResource("/menu/smallFind.png"));
        btnFind.setIcon(iconFind);
        ImageIcon iconModify = new ImageIcon(getClass().getResource("/menu/findmedium.png"));
        headerFind.setIcon(iconModify);
        this.lblName.setText(user.getUserid());
        //setResizable(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonthYearIC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonthYearIC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonthYearIC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonthYearIC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonthYearIC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnFind;
    private javax.swing.JLabel headerFind;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JTextField txtFromMonth;
    private javax.swing.JTextField txtFromYear;
    private javax.swing.JTextField txtIC;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtToMonth;
    private javax.swing.JTextField txtToYear;
    // End of variables declaration//GEN-END:variables
}
