/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import javaClass.GrassMedicinePotion;
import javaClass.GrassMedicinePill;
import javaClass.TraditionalMedicinePotion;
import javaClass.TraditionalMedicinePill;
import javaClass.User;
import javaClass.Code;
import java.sql.SQLException;
import java.util.HashMap;
import javaClass.PrintTemplate;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Sheng
 */
public class NewMedicine extends javax.swing.JFrame {

    /**
     * Creates new form NewMedicine
     */
    private User user;
    private String userid = "";
    
    public NewMedicine() {
        initComponents();
    }

    public NewMedicine(User user) {        
        this.user = user;
        initComponents();
        userid = user.getUserid();
        image();
        setResizable(false);
        comboMedicine();
        if(comboMedicine.getSelectedItem().equals("单味药粉"))
        {
            lblzhucheng.setText("药性:"); 
            lblzhuzi.setText("应用:"); 
        }
        else
        {
            lblzhucheng.setText("组成:"); 
            lblzhuzi.setText("主治:"); 
        }
         changeLabel();
         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        lbllogo = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        headerMedic = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        panelBody = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboMedicine = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblzhucheng = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtComponent = new javax.swing.JTextArea();
        lblzhuzi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtIndication = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txtEffect = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtScoop = new javax.swing.JTextField();
        lblWeight1 = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        lblCost = new javax.swing.JLabel();
        txtCost = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        lblWeight = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        panelHeader.setBackground(new java.awt.Color(255, 204, 204));
        panelHeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        panelHeader.setForeground(new java.awt.Color(153, 153, 153));
        panelHeader.setLayout(null);
        panelHeader.add(lbllogo);
        lbllogo.setBounds(14, 2, 231, 70);

        jLabel17.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        jLabel17.setText("登入：");
        panelHeader.add(jLabel17);
        jLabel17.setBounds(1651, 2, 75, 70);

        lblName.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        panelHeader.add(lblName);
        lblName.setBounds(1720, 0, 160, 70);

        headerMedic.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        headerMedic.setText("新增药");
        panelHeader.add(headerMedic);
        headerMedic.setBounds(870, 0, 160, 70);

        getContentPane().add(panelHeader);
        panelHeader.setBounds(0, 0, 1940, 70);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("CopyRight © Heng Seng Tong");
        jPanel1.add(jLabel18);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 940, 1940, 50);

        panelBody.setBackground(new java.awt.Color(255, 255, 255));
        panelBody.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        panelBody.setLayout(null);

        jLabel1.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel1.setText("药：");
        panelBody.add(jLabel1);
        jLabel1.setBounds(190, 40, 38, 40);

        comboMedicine.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        comboMedicine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboMedicineMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                comboMedicineMouseExited(evt);
            }
        });
        comboMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMedicineActionPerformed(evt);
            }
        });
        comboMedicine.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboMedicineKeyPressed(evt);
            }
        });
        panelBody.add(comboMedicine);
        comboMedicine.setBounds(270, 40, 120, 40);

        jLabel2.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel2.setText("名字：");
        panelBody.add(jLabel2);
        jLabel2.setBounds(170, 100, 57, 40);

        txtName.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        panelBody.add(txtName);
        txtName.setBounds(270, 100, 840, 40);

        lblzhucheng.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        lblzhucheng.setText("组成：");
        panelBody.add(lblzhucheng);
        lblzhucheng.setBounds(170, 160, 70, 30);

        txtComponent.setColumns(20);
        txtComponent.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        txtComponent.setRows(5);
        jScrollPane2.setViewportView(txtComponent);

        panelBody.add(jScrollPane2);
        jScrollPane2.setBounds(270, 160, 840, 100);

        lblzhuzi.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        lblzhuzi.setText("主治：");
        panelBody.add(lblzhuzi);
        lblzhuzi.setBounds(170, 280, 70, 30);

        txtIndication.setColumns(20);
        txtIndication.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        txtIndication.setRows(5);
        jScrollPane1.setViewportView(txtIndication);

        panelBody.add(jScrollPane1);
        jScrollPane1.setBounds(270, 280, 840, 100);

        jLabel4.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel4.setText("功效：");
        panelBody.add(jLabel4);
        jLabel4.setBounds(160, 400, 57, 40);

        txtEffect.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        panelBody.add(txtEffect);
        txtEffect.setBounds(270, 400, 840, 40);

        jLabel5.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel5.setText("每次每日分量：");
        panelBody.add(jLabel5);
        jLabel5.setBounds(90, 460, 140, 40);

        txtScoop.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        panelBody.add(txtScoop);
        txtScoop.setBounds(270, 460, 840, 40);

        lblWeight1.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        lblWeight1.setText("重量：");
        panelBody.add(lblWeight1);
        lblWeight1.setBounds(150, 520, 60, 40);

        txtWeight.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        panelBody.add(txtWeight);
        txtWeight.setBounds(270, 520, 780, 40);

        lblCost.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        lblCost.setText("本钱 RM/GM：RM");
        panelBody.add(lblCost);
        lblCost.setBounds(90, 580, 180, 40);

        txtCost.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        panelBody.add(txtCost);
        txtCost.setBounds(270, 580, 840, 40);

        lblPrice.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        lblPrice.setText("价格 RM/GM：RM");
        panelBody.add(lblPrice);
        lblPrice.setBounds(90, 640, 180, 40);

        txtPrice.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        panelBody.add(txtPrice);
        txtPrice.setBounds(270, 640, 840, 40);

        btnBack.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        btnBack.setText("退出");
        btnBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        panelBody.add(btnBack);
        btnBack.setBounds(140, 700, 130, 60);

        btnAdd.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        btnAdd.setText("新增");
        btnAdd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        panelBody.add(btnAdd);
        btnAdd.setBounds(980, 700, 130, 60);

        lblWeight.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        lblWeight.setText("GM");
        panelBody.add(lblWeight);
        lblWeight.setBounds(1060, 520, 50, 40);

        btnPrint.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        btnPrint.setText("打印");
        btnPrint.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        panelBody.add(btnPrint);
        btnPrint.setBounds(840, 700, 130, 60);

        getContentPane().add(panelBody);
        panelBody.setBounds(390, 100, 1200, 820);

        setBounds(0, 0, 1955, 1034);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        try
        {
            String name = txtName.getText();
            String component = txtComponent.getText();
            String indication = txtIndication.getText();
            String effect = txtEffect.getText();
            String scoop = txtScoop.getText();
            String weight = txtWeight.getText();
            String cost = txtCost.getText();
            String price = txtPrice.getText();
            
            if(name.equalsIgnoreCase(""))
            {
                JOptionPane.showMessageDialog(rootPane, "请填写名字！");
            }
            else if(component.equalsIgnoreCase(""))
            {
                if(comboMedicine.getSelectedItem().equals("单味药粉"))
                {
                    JOptionPane.showMessageDialog(rootPane, "请填写药性！");
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "请填写组成！");
                }
            }
            else if(indication.equalsIgnoreCase(""))
            {
                if(comboMedicine.getSelectedItem().equals("单味药粉"))
                {
                    JOptionPane.showMessageDialog(rootPane, "请填写应用！");
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "请填写主治！");
                }
            }
            else if(effect.equalsIgnoreCase(""))
            {
                JOptionPane.showMessageDialog(rootPane, "请填写功效！");
            }
            else if(scoop.equalsIgnoreCase(""))
            {
                JOptionPane.showMessageDialog(rootPane, "请填写每次每日分量！");
            }
            else if(weight.equalsIgnoreCase(""))
            {
                JOptionPane.showMessageDialog(rootPane, "请填写重量！");
            }
            else if(cost.equalsIgnoreCase(""))
            {
                JOptionPane.showMessageDialog(rootPane, "请填写本钱！");
            }
            else if(price.equalsIgnoreCase(""))
            {
                JOptionPane.showMessageDialog(rootPane, "请填写价格！");
            }
            else
            {
                HashMap<String,String> map = new HashMap<String, String>();

                float scoop1 = Float.valueOf(txtScoop.getText());
                float weight1= Float.valueOf(txtWeight.getText());
                float cost1 = Float.valueOf(txtCost.getText());
                float price1 = Float.valueOf(txtPrice.getText());

                optionMessage(component,indication,effect,scoop,weight,cost,price);
                
                if(comboMedicine.getSelectedItem().equals("复方药粉")) // traitional medicine potion
                {
                    TraditionalMedicinePotion pill = new TraditionalMedicinePotion();
                    map = pill.AddTraditionalMedicinePotion(name, component, effect, indication, scoop1, price1, weight1, cost1, "", "","TradMedPo",userid);
                    if(map.get("returnMessage").equalsIgnoreCase("1"))
                    {
                        JOptionPane.showMessageDialog(rootPane, "复方药粉已新增！ID 是 "+map.get("ID"));
                        clearTextBox();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(rootPane, map.get("returnMessage"));
                    }
                }
                else if(comboMedicine.getSelectedItem().equals("药丸")) //grass medicine pill
                {
                    GrassMedicinePill pill = new GrassMedicinePill();
                    map = pill.AddGrassMedicinePill(name, component, effect, indication, scoop1, price1, weight1, cost1, "", "","GrasMedPi",userid);
                    if(map.get("returnMessage").equalsIgnoreCase("1"))
                    {
                        JOptionPane.showMessageDialog(rootPane, "药丸已新增！ID 是 "+map.get("ID"));
                        clearTextBox();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(rootPane, map.get("returnMessage"));
                    }
                }
                else if(comboMedicine.getSelectedItem().equals("药水"))// grass medicine potion
                {
                    GrassMedicinePotion pill = new GrassMedicinePotion();
                    map = pill.AddGrassMedicinePotion(name, component, effect, indication, scoop1, price1, weight1, cost1, "", "","GrasMedPo",userid);
                    if(map.get("returnMessage").equalsIgnoreCase("1"))
                    {
                        JOptionPane.showMessageDialog(rootPane, "药水已新增！ID 是 "+map.get("ID"));
                        clearTextBox();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(rootPane, map.get("returnMessage"));
                    }
                }
                else if(comboMedicine.getSelectedItem().equals("单味药粉"))// traitional medicine pill
                {
                    TraditionalMedicinePill pill = new TraditionalMedicinePill();
                    map = pill.AddTraditionalMedicinePill(name, effect, scoop1, price1, weight1, cost1,"","", component, indication,"TradMedPi",userid);
                    if(map.get("returnMessage").equalsIgnoreCase("1"))
                    {
                        JOptionPane.showMessageDialog(rootPane, "单调药粉已新增！ID 是 "+map.get("ID"));
                        clearTextBox();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(rootPane, map.get("returnMessage"));
                    }
                }
            }
        } catch (NumberFormatException number){
            JOptionPane.showMessageDialog(rootPane, "每次每日分量，重量，本钱和价格不可以有字母！");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        MedicalDetailMenu menu = new MedicalDetailMenu(user);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void comboMedicineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboMedicineMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMedicineMouseClicked

    private void comboMedicineMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboMedicineMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_comboMedicineMouseExited

    private void comboMedicineKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboMedicineKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMedicineKeyPressed

    private void comboMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMedicineActionPerformed
        // TODO add your handling code here:
        if(comboMedicine.getSelectedItem().equals("单味药粉"))
        {
            lblzhucheng.setText("药性:"); 
            lblzhuzi.setText("应用:"); 
        }
        else
        {
            lblzhucheng.setText("组成:"); 
            lblzhuzi.setText("主治:"); 
        }
        changeLabel();
        
        clearTextBox();
    }//GEN-LAST:event_comboMedicineActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        String medicine = comboMedicine.getSelectedItem().toString();
        String Name = txtName.getText();
        String component = txtComponent.getText();
        String indication = txtIndication.getText();
        String effect = txtEffect.getText();
        String scoop = txtScoop.getText();
        String weight = txtWeight.getText();
        String cost = txtCost.getText();
        String price = txtPrice.getText();
        
        String bodyContent = printPreview(medicine,Name,component,indication,effect,scoop,weight,cost,price);
        PrintForm main = new PrintForm(user,5,bodyContent);
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPrintActionPerformed
    
    public void optionMessage(String component,String indication, String effect, String scoop, String weight, String cost, String price){
        if(!comboMedicine.getSelectedItem().equals("单味药粉"))
        {
            if(component.equalsIgnoreCase(""))
            {
                JOptionPane.showMessageDialog(rootPane,"组成没填！");
            }
            else if(indication.equalsIgnoreCase(""))
            {
                JOptionPane.showMessageDialog(rootPane,"主治没填！");
            }
            else
            {
                validateMessage(effect, scoop, weight, cost, price);
            }
        } 
        else if(comboMedicine.getSelectedItem().equals("单味药粉"))
        {
            if(component.equalsIgnoreCase(""))
            {
                JOptionPane.showMessageDialog(rootPane,"药性没填！");
            }
            else if(indication.equalsIgnoreCase(""))
            {
                JOptionPane.showMessageDialog(rootPane,"应用没填！");
            }
            else
            {
                validateMessage(effect, scoop, weight, cost, price);
            }
        }
        
    }
    
    public void validateMessage(String effect, String scoop, String weight, String cost, String price){
        if(effect.equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(rootPane,"功效没填！");
        }
        else if(scoop.equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(rootPane,"每次每日分量没填！");
        }
        else if(weight.equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(rootPane,"重量没填！");
        }
        else if(cost.equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(rootPane,"本钱没填！");
        }
        else if(price.equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(rootPane,"价格没填！");
        }
    }
    
    public void comboMedicine()
    {
        try {
            Code code = new Code();
            
            for(int i = 0; i < code.getComboMedicine(userid).size(); i++)
            {
                System.out.println(code.getComboMedicine(userid).get(i).toString());
                comboMedicine.addItem(code.getComboMedicine(userid).get(i).getCode());
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }
    
    public void changeLabel()
    {
        if(comboMedicine.getSelectedItem().equals("药丸"))
        {
            lblWeight.setText("'S");
            lblCost.setText("本钱 RM/'S: RM");
            lblPrice.setText("价格 RM/'S: RM");
        }
        else if(comboMedicine.getSelectedItem().equals("药水"))
        {
            lblWeight.setText("ML");
            lblCost.setText("本钱 RM/10 ML: RM");
            lblPrice.setText("价格 RM/10 ML: RM");
        }
        else
        {
            lblWeight.setText("GM");
            lblCost.setText("本钱 RM/GM: RM");
            lblPrice.setText("价格 RM/GM: RM");
        }
    }
    
    public void clearTextBox()
    {
        txtName.setText("");
        txtComponent.setText("");
        txtIndication.setText("");
        txtEffect.setText("");
        txtScoop.setText("");
        txtWeight.setText("");
        txtCost.setText("");
        txtPrice.setText("");
    }
    
    public void image()
    {
        ImageIcon iconLogo = new ImageIcon(getClass().getResource("/menu/hengsengtong.png"));
        lbllogo.setIcon(iconLogo);
        ImageIcon iconBack = new ImageIcon(getClass().getResource("/menu/smallBack.png"));
        btnBack.setIcon(iconBack);
        ImageIcon iconAdd = new ImageIcon(getClass().getResource("/menu/addsmall.png"));
        btnAdd.setIcon(iconAdd);
        ImageIcon iconHeader = new ImageIcon(getClass().getResource("/menu/addmedium.png"));
        headerMedic.setIcon(iconHeader);
        ImageIcon iconPrint = new ImageIcon(getClass().getResource("/menu/smallprint.png"));
        btnPrint.setIcon(iconPrint);
        this.lblName.setText(user.getUserid());
        setResizable(false);
    }
    
    public String printPreview(String medicine, String Name, String component, String indication, String effect, String scoop, String weight, String cost, String price)
    {
        PrintTemplate print = new PrintTemplate();
        return print.printMedicine(medicine,Name,component,indication,effect,scoop,weight,cost,price);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewMedicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPrint;
    private javax.swing.JComboBox<String> comboMedicine;
    private javax.swing.JLabel headerMedic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCost;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JLabel lblWeight1;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JLabel lblzhucheng;
    private javax.swing.JLabel lblzhuzi;
    private javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JTextArea txtComponent;
    private javax.swing.JTextField txtCost;
    private javax.swing.JTextField txtEffect;
    private javax.swing.JTextArea txtIndication;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtScoop;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
