/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

//import com.lowagie.text.Document;
//import com.lowagie.text.DocumentException;
//import com.lowagie.text.pdf.PdfPTable;
//import com.lowagie.text.pdf.PdfWriter;
import javaClass.Excel;
import javaClass.User;
import java.awt.Component;
import java.awt.Dimension;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.PdfPTable;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import javax.swing.ImageIcon;
import javax.swing.table.JTableHeader;
/**
 *
 * @author Sheng
 */
public class PrintPatientReport extends javax.swing.JFrame {

    /**
     * Creates new form ImportJtable
     */
    private User user;
    Double bHeight=0.0;
    public PrintPatientReport(User user) {
        initComponents();
        this.user = user;
        JTableHeader tableHeader = tblImport.getTableHeader();
        tableHeader.setFont(new Font("STXihei", Font.BOLD, 18));
        setResizable(false);
    }
    public PrintPatientReport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnImport = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblImport = new javax.swing.JTable();
        printicon = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnImport.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        btnImport.setText("Import");
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });
        getContentPane().add(btnImport);
        btnImport.setBounds(790, 780, 105, 48);

        btnPrint.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        btnPrint.setText("打印");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrint);
        btnPrint.setBounds(920, 780, 105, 48);

        btnBack.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        btnBack.setText("退出");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(1050, 780, 102, 50);

        tblImport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IC", "姓名", "性别 ", "年龄 ", "电话号码 ", "地址", "更新时间", "创建时间"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblImport);

        jScrollPane2.setViewportView(jScrollPane1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 220, 1140, 490);

        printicon.setText("print whole");
        printicon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printiconActionPerformed(evt);
            }
        });
        getContentPane().add(printicon);
        printicon.setBounds(650, 780, 97, 25);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 20, 570, 190);

        setBounds(0, 0, 1361, 929);
    }// </editor-fold>//GEN-END:initComponents
    DefaultTableModel model;
    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
        // TODO add your handling code here:

        DefaultTableModel ImportDataFromExcelModel = (DefaultTableModel) tblImport.getModel();
        FileInputStream excelFIS = null;
        BufferedInputStream excelBIS = null;
        XSSFWorkbook excelImportWorkBook = null;
        String currentDirectoryPath = "C:\\Users\\Sheng\\Desktop";
        JFileChooser excelFileChooserImport = new JFileChooser(currentDirectoryPath);

        int excelChooser = excelFileChooserImport.showOpenDialog(null);

        if (excelChooser == JFileChooser.APPROVE_OPTION) {
            try {
                File excelFile = excelFileChooserImport.getSelectedFile();
                excelFIS = new FileInputStream(excelFile);
                excelBIS = new BufferedInputStream(excelFIS);
                excelImportWorkBook = new XSSFWorkbook(excelBIS);
                XSSFSheet excelSheet = excelImportWorkBook.getSheetAt(0);

                for (int i = 0; i <= excelSheet.getLastRowNum(); i++) {
                    XSSFRow excelRow = excelSheet.getRow(i);
                    XSSFCell IC = excelRow.getCell(0);
                    XSSFCell name = excelRow.getCell(1);
                    XSSFCell gender = excelRow.getCell(2);
                    XSSFCell age = excelRow.getCell(3);
                    XSSFCell phone = excelRow.getCell(4);
                    XSSFCell address = excelRow.getCell(5);
                    XSSFCell lastUpdateDateTime = excelRow.getCell(6);
                    XSSFCell createDateTime = excelRow.getCell(7);
                    if (i != 0) {
                        tblImport.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
                        TableColumnModel columnModel = tblImport.getColumnModel();
                        columnModel.getColumn(0).setPreferredWidth(100);
                        columnModel.getColumn(1).setPreferredWidth(150);
                        columnModel.getColumn(2).setPreferredWidth(50);
                        columnModel.getColumn(3).setPreferredWidth(40);
                        columnModel.getColumn(4).setPreferredWidth(90);
                        columnModel.getColumn(5).setPreferredWidth(530);
                        columnModel.getColumn(6).setPreferredWidth(170);
                        columnModel.getColumn(7).setPreferredWidth(170);
                        ImportDataFromExcelModel.addRow(new Object[]{IC, name, gender, age, phone, address, lastUpdateDateTime, createDateTime});
                    }
                }
                JOptionPane.showMessageDialog(null, "Imported Successfully......");
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "File Not Found");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "ImportJtable.btnImportActionPerformed get error on line 189"+ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnImportActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        Excel exl = new Excel();
        exl.Print(tblImport);
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        PatientDetailMenu detail = new PatientDetailMenu(user);
        detail.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void printiconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printiconActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("");
        //tblImport.print(JTable.PrintMode.NORMAL, header, header);
        //bHeight = Double.valueOf(itemName.size());
        //JOptionPane.showMessageDialog(rootPane, bHeight);
        
        PrinterJob pj = PrinterJob.getPrinterJob();        
        pj.setPrintable(new BillPrintable(),getPageFormat(pj));
        try {
             pj.print();
          
        }
         catch (PrinterException ex) {
                 ex.printStackTrace();
        }
    }//GEN-LAST:event_printiconActionPerformed

    public PageFormat getPageFormat(PrinterJob pj)
    {
    
        PageFormat pf = pj.defaultPage();
        Paper paper = pf.getPaper();    

        double bodyHeight = bHeight;  
        double headerHeight = 5.0;                  
        double footerHeight = 5.0;        
        double width = cm_to_pp(8); 
        double height = cm_to_pp(headerHeight+bodyHeight+footerHeight); 
        paper.setSize(width, height);
        paper.setImageableArea(0,10,width,height - cm_to_pp(1));  

        pf.setOrientation(PageFormat.PORTRAIT);  
        pf.setPaper(paper);    

        return pf;
    }
    
    protected static double cm_to_pp(double cm)
    {            
	        return toPPI(cm * 0.393600787);            
    }
 
    protected static double toPPI(double inch)
    {            
                return inch * 72d;            
    }

    
    public class BillPrintable implements Printable {
        public int print(Graphics graphics, PageFormat pageFormat,int pageIndex) throws PrinterException 
      {   
          ImageIcon icon=new ImageIcon("C:\\Users\\Sheng\\Desktop\\heng-seng-tong-03.png"); 
          int result = NO_SUCH_PAGE;    
            if (pageIndex == 0) {                    

                Graphics2D g2d = (Graphics2D) graphics;                    
                double width = pageFormat.getImageableWidth();                               
                g2d.translate((int) pageFormat.getImageableX(),(int) pageFormat.getImageableY()); 



              //  FontMetrics metrics=g2d.getFontMetrics(new Font("Arial",Font.BOLD,7));

            try{
                int y=20;
                int yShift = 10;
                int headerRectHeight=15;
               // int headerRectHeighta=40;


                g2d.setFont(new Font("Monospaced",Font.PLAIN,9));
                g2d.drawImage(icon.getImage(), 50, 20, 90, 30, rootPane);y+=yShift+30;
                g2d.drawString("-------------------------------------",12,y);y+=yShift;
                g2d.drawString("         CodeGuid.com        ",12,y);y+=yShift;
                g2d.drawString("   No 00000 Address Line One ",12,y);y+=yShift;
                g2d.drawString("   Address Line 02 SRI LANKA ",12,y);y+=yShift;
                g2d.drawString("   www.facebook.com/CodeGuid ",12,y);y+=yShift;
                g2d.drawString("        +94700000000      ",12,y);y+=yShift;
                g2d.drawString("-------------------------------------",12,y);y+=headerRectHeight;

                g2d.drawString(" Item Name                  Price   ",10,y);y+=yShift;
                g2d.drawString("-------------------------------------",10,y);y+=headerRectHeight;

               /* for(int s=0; s<r; s++)
                {
                g2d.drawString(" "+itemName.get(s)+"                            ",10,y);y+=yShift;
                g2d.drawString("      "+quantity.get(s)+" * "+itemPrice.get(s),10,y); g2d.drawString(subtotal.get(s),160,y);y+=yShift;

                }

                g2d.drawString("-------------------------------------",10,y);y+=yShift;
                g2d.drawString(" Total amount:               "+txttotalAmount.getText()+"   ",10,y);y+=yShift;
                g2d.drawString("-------------------------------------",10,y);y+=yShift;
                g2d.drawString(" Cash      :                 "+txtcash.getText()+"   ",10,y);y+=yShift;
                g2d.drawString("-------------------------------------",10,y);y+=yShift;
                g2d.drawString(" Balance   :                 "+txtbalance.getText()+"   ",10,y);y+=yShift;

                g2d.drawString("*************************************",10,y);y+=yShift;
                g2d.drawString("       THANK YOU COME AGAIN            ",10,y);y+=yShift;
                g2d.drawString("*************************************",10,y);y+=yShift;
                g2d.drawString("       SOFTWARE BY:CODEGUID          ",10,y);y+=yShift;
                g2d.drawString("   CONTACT: contact@codeguid.com       ",10,y);y+=yShift; */      


        }
        catch(Exception e){
        e.printStackTrace();
        }
            }
              result = PAGE_EXISTS;    
              
          return result;    
      }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintPatientReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintPatientReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintPatientReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintPatientReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new PrintPatientReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnImport;
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton printicon;
    private javax.swing.JTable tblImport;
    // End of variables declaration//GEN-END:variables
}
