/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.Color;
import java.awt.Font;
import medical.LoginUI;
import javaClass.User;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;
import medical.LoginUI2;

/**
 *
 * @author Sheng
 */
public class RegisterNewUser extends javax.swing.JFrame {

    /**
     * Creates new form RegisterNewUser
     */
    public RegisterNewUser() {
        initComponents();
        //lblEmail.setVisible(false);
        lblConfirmEmail.setVisible(false);
//        txtEmail.setVisible(false);
//        txtConfirnEmail.setVisible(false);
        image();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        lbllogo = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtPassword = new javax.swing.JPasswordField();
        btnConfirm = new javax.swing.JButton();
        txtUserid = new javax.swing.JTextField();
        txtConfirmPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblConfirmEmail = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtConfirmID = new javax.swing.JTextField();
        comboSecurityQuestion1 = new javax.swing.JComboBox<>();
        lblConfirmEmail2 = new javax.swing.JLabel();
        comboSecurityQuestion2 = new javax.swing.JComboBox<>();
        lblConfirmEmail3 = new javax.swing.JLabel();
        comboSecurityQuestion3 = new javax.swing.JComboBox<>();
        txtSecurityAnswer3 = new javax.swing.JTextField();
        txtSecurityAnswer1 = new javax.swing.JTextField();
        txtSecurityAnswer2 = new javax.swing.JTextField();
        lblConfirmEmail4 = new javax.swing.JLabel();
        lblConfirmEmail5 = new javax.swing.JLabel();
        lblConfirmEmail6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtConfirmEmail = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        panelHeader.setBackground(new java.awt.Color(255, 204, 204));
        panelHeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        panelHeader.setForeground(new java.awt.Color(153, 153, 153));
        panelHeader.setLayout(null);
        panelHeader.add(lbllogo);
        lbllogo.setBounds(14, 2, 231, 70);

        jLabel20.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        jLabel20.setText("登入：");
        panelHeader.add(jLabel20);
        jLabel20.setBounds(1160, 0, 75, 70);

        lblName.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        panelHeader.add(lblName);
        lblName.setBounds(1240, 0, 127, 70);

        jLabel4.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        jLabel4.setText("注册新账号");
        panelHeader.add(jLabel4);
        jLabel4.setBounds(540, 0, 260, 70);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        jPanel2.setLayout(null);

        txtPassword.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jPanel2.add(txtPassword);
        txtPassword.setBounds(60, 70, 470, 39);

        btnConfirm.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        btnConfirm.setText("确认");
        btnConfirm.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        jPanel2.add(btnConfirm);
        btnConfirm.setBounds(980, 480, 130, 50);

        txtUserid.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jPanel2.add(txtUserid);
        txtUserid.setBounds(60, 20, 470, 37);

        txtConfirmPassword.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jPanel2.add(txtConfirmPassword);
        txtConfirmPassword.setBounds(630, 70, 480, 40);

        jLabel1.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel1.setText("确定账号：");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(540, 20, 100, 40);

        jLabel2.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel2.setText("密码：");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 70, 60, 40);

        jLabel3.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel3.setText("确认密码：");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(540, 70, 100, 40);

        lblConfirmEmail.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        lblConfirmEmail.setText("答案3:");
        jPanel2.add(lblConfirmEmail);
        lblConfirmEmail.setBounds(10, 420, 100, 40);

        jLabel6.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel6.setText("账号：");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 20, 80, 40);

        txtConfirmID.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jPanel2.add(txtConfirmID);
        txtConfirmID.setBounds(630, 20, 480, 37);

        comboSecurityQuestion1.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jPanel2.add(comboSecurityQuestion1);
        comboSecurityQuestion1.setBounds(110, 170, 1000, 40);

        lblConfirmEmail2.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        lblConfirmEmail2.setText("安全问题2:");
        jPanel2.add(lblConfirmEmail2);
        lblConfirmEmail2.setBounds(10, 270, 100, 40);

        comboSecurityQuestion2.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jPanel2.add(comboSecurityQuestion2);
        comboSecurityQuestion2.setBounds(110, 270, 1000, 40);

        lblConfirmEmail3.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        lblConfirmEmail3.setText("安全问题3:");
        jPanel2.add(lblConfirmEmail3);
        lblConfirmEmail3.setBounds(10, 370, 100, 40);

        comboSecurityQuestion3.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jPanel2.add(comboSecurityQuestion3);
        comboSecurityQuestion3.setBounds(110, 370, 1000, 40);

        txtSecurityAnswer3.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jPanel2.add(txtSecurityAnswer3);
        txtSecurityAnswer3.setBounds(110, 420, 1000, 40);

        txtSecurityAnswer1.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        txtSecurityAnswer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSecurityAnswer1ActionPerformed(evt);
            }
        });
        jPanel2.add(txtSecurityAnswer1);
        txtSecurityAnswer1.setBounds(110, 220, 1000, 40);

        txtSecurityAnswer2.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jPanel2.add(txtSecurityAnswer2);
        txtSecurityAnswer2.setBounds(110, 320, 1000, 40);

        lblConfirmEmail4.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        lblConfirmEmail4.setText("安全问题1:");
        jPanel2.add(lblConfirmEmail4);
        lblConfirmEmail4.setBounds(10, 170, 100, 40);

        lblConfirmEmail5.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        lblConfirmEmail5.setText("答案1:");
        jPanel2.add(lblConfirmEmail5);
        lblConfirmEmail5.setBounds(10, 220, 100, 40);

        lblConfirmEmail6.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        lblConfirmEmail6.setText("答案2:");
        jPanel2.add(lblConfirmEmail6);
        lblConfirmEmail6.setBounds(10, 320, 100, 40);

        jLabel5.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel5.setText("电子邮件:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 120, 90, 40);

        jLabel7.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel7.setText("确认电子邮件:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(540, 120, 120, 40);

        btnBack.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        btnBack.setText("退出");
        btnBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack);
        btnBack.setBounds(10, 480, 130, 50);

        txtConfirmEmail.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jPanel2.add(txtConfirmEmail);
        txtConfirmEmail.setBounds(670, 120, 440, 37);

        txtEmail.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jPanel2.add(txtEmail);
        txtEmail.setBounds(100, 120, 430, 37);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("CopyRight © Heng Seng Tong");
        jPanel6.add(jLabel14);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 1370, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 1370, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1127, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane1.setViewportView(jPanel3);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 1370, 700);

        setBounds(0, 0, 1384, 742);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        String userid = txtUserid.getText();
        String confirmuserid = txtConfirmID.getText();
        String password = txtPassword.getText();
        String confirmpassword = txtConfirmPassword.getText();
        String email = txtEmail.getText();
        String confirmEmail = txtConfirmEmail.getText();
        String securityQue1 = comboSecurityQuestion1.getSelectedItem().toString();
        String securityQue2 = comboSecurityQuestion2.getSelectedItem().toString();
        String securityQue3 = comboSecurityQuestion3.getSelectedItem().toString();
        String securityAns1 = txtSecurityAnswer1.getText();
        String securityAns2 = txtSecurityAnswer2.getText();
        String securityAns3 = txtSecurityAnswer3.getText();
        
        if(userid.equalsIgnoreCase(confirmuserid))
        {
            if(password.equalsIgnoreCase(confirmpassword))
            {
                if(email.equalsIgnoreCase(confirmEmail))
                {
                    try {
                        User user = new User(userid, password,"Admin",1,email,securityQue1,securityAns1,securityQue2,securityAns2,securityQue3,securityAns3);
                        String result = user.registerUser();
                        if(result.equalsIgnoreCase("1"))
                        {
                            JOptionPane.showMessageDialog(rootPane, "注册成功！");
                            LoginUI2 loginui = new LoginUI2();
                            loginui.setVisible(true);
                            this.dispose();
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(rootPane, result);
                        }
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(rootPane, "RegisterNewUser.btnConfirmActionPerformed get error on line 124,"+ex.getMessage());
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "电子邮件和确认电子邮件不相对！");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "密码和确认密码不相对！");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "账号和确认账号不相对！");
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void txtSecurityAnswer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSecurityAnswer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSecurityAnswer1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        LoginUI2 register = new LoginUI2();
        register.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    public void image()
    {
        ImageIcon iconLogo = new ImageIcon(getClass().getResource("/menu/hengsengtong.png"));
        lbllogo.setIcon(iconLogo);
        ImageIcon iconBack = new ImageIcon(getClass().getResource("/menu/smallBack.png"));
        btnBack.setIcon(iconBack);
        ImageIcon iconHeader = new ImageIcon(getClass().getResource("/menu/accountmedium.png"));
        jLabel4.setIcon(iconHeader);
        ImageIcon iconConfrim = new ImageIcon(getClass().getResource("/menu/smallconfirm.png"));
        btnConfirm.setIcon(iconConfrim);
        setResizable(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterNewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterNewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterNewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterNewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterNewUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JComboBox<String> comboSecurityQuestion1;
    private javax.swing.JComboBox<String> comboSecurityQuestion2;
    private javax.swing.JComboBox<String> comboSecurityQuestion3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblConfirmEmail;
    private javax.swing.JLabel lblConfirmEmail2;
    private javax.swing.JLabel lblConfirmEmail3;
    private javax.swing.JLabel lblConfirmEmail4;
    private javax.swing.JLabel lblConfirmEmail5;
    private javax.swing.JLabel lblConfirmEmail6;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JTextField txtConfirmEmail;
    private javax.swing.JTextField txtConfirmID;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtSecurityAnswer1;
    private javax.swing.JTextField txtSecurityAnswer2;
    private javax.swing.JTextField txtSecurityAnswer3;
    private javax.swing.JTextField txtUserid;
    // End of variables declaration//GEN-END:variables
}
