/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.Color;
import javaClass.Patient;
import javaClass.User;
import java.awt.Font;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.List;
import javaClass.TablePrintable;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Sheng
 */
public class SearchPatient extends javax.swing.JFrame {

    /**
     * Creates new form SearchPatient
     */
    private User user;
    DefaultTableModel model;
    private String userid="";
    
    public SearchPatient() {
        initComponents();
    }

    public SearchPatient(User user) throws SQLException {
        this.user = user;
        userid = user.getUserid();
        initComponents();
        JTableHeader tableHeader = tblPatient.getTableHeader();
        tableHeader.setFont(new Font("STXihei", Font.BOLD, 18));
        show_patients();
        image();
        widthTable();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        panelHeader = new javax.swing.JPanel();
        lbllogo = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboArrange = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPatient = new javax.swing.JTable();
        btnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(591, 554, 0, 0);

        panelHeader.setBackground(new java.awt.Color(255, 204, 204));
        panelHeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        panelHeader.setForeground(new java.awt.Color(153, 153, 153));
        panelHeader.setLayout(null);
        panelHeader.add(lbllogo);
        lbllogo.setBounds(14, 2, 231, 70);

        jLabel20.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        jLabel20.setText("登入：");
        panelHeader.add(jLabel20);
        jLabel20.setBounds(1670, 5, 75, 60);

        lblName.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        panelHeader.add(lblName);
        lblName.setBounds(1752, 5, 127, 60);

        jLabel9.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        jLabel9.setText("寻找病人资料");
        panelHeader.add(jLabel9);
        jLabel9.setBounds(880, 0, 240, 70);

        getContentPane().add(panelHeader);
        panelHeader.setBounds(0, 0, 1940, 70);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("CopyRight © Heng Seng Tong");
        jPanel1.add(jLabel21);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 940, 1940, 50);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        jPanel2.setLayout(null);

        txtID.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIDKeyPressed(evt);
            }
        });
        jPanel2.add(txtID);
        txtID.setBounds(160, 80, 490, 42);

        jLabel1.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel1.setText("ID:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(120, 80, 107, 42);

        jLabel4.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel4.setText("IC:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(120, 150, 40, 40);

        txtIC.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        txtIC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtICKeyPressed(evt);
            }
        });
        jPanel2.add(txtIC);
        txtIC.setBounds(160, 150, 490, 40);

        jLabel5.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel5.setText("姓名：");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(110, 220, 57, 40);

        txtName.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
        });
        jPanel2.add(txtName);
        txtName.setBounds(160, 220, 490, 40);

        jLabel6.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel6.setText("性别：");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(110, 300, 60, 40);

        txtGender.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        txtGender.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtGenderKeyPressed(evt);
            }
        });
        jPanel2.add(txtGender);
        txtGender.setBounds(160, 300, 490, 40);

        jLabel7.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel7.setText("年龄：");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(100, 380, 57, 40);

        txtAge.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAgeKeyPressed(evt);
            }
        });
        jPanel2.add(txtAge);
        txtAge.setBounds(160, 380, 490, 40);

        jLabel8.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel8.setText("电话号码：");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(70, 460, 100, 40);

        txtPhone.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPhoneKeyPressed(evt);
            }
        });
        jPanel2.add(txtPhone);
        txtPhone.setBounds(160, 460, 490, 40);

        jLabel3.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel3.setText("排列：");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(90, 540, 60, 42);

        comboArrange.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        comboArrange.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "顺序", "逆序" }));
        jPanel2.add(comboArrange);
        comboArrange.setBounds(160, 540, 150, 40);

        btnBack.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        btnBack.setText("退出");
        btnBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack);
        btnBack.setBounds(80, 640, 130, 50);

        btnFind.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        btnFind.setText("寻找");
        btnFind.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        jPanel2.add(btnFind);
        btnFind.setBounds(520, 640, 130, 50);

        tblPatient.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        tblPatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "IC", "姓名", "性别", "年龄", "电话号码", "地址", "创建时间", "更新时间"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblPatient.setRowHeight(25);
        tblPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPatientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPatient);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(680, 60, 1110, 630);

        btnPrint.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        btnPrint.setText("打印");
        btnPrint.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel2.add(btnPrint);
        btnPrint.setBounds(370, 640, 130, 50);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(50, 90, 1840, 780);

        setBounds(0, 0, 1959, 1034);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void tblPatientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPatientMouseClicked
        // TODO add your handling code here:
        int index = tblPatient.getSelectedRow();
        TableModel model = tblPatient.getModel();
        String ID = model.getValueAt(index, 0).toString();
        String IC = model.getValueAt(index,1).toString();
        String Name = model.getValueAt(index,2).toString();
        String Gender = model.getValueAt(index,3).toString();
        String Age = model.getValueAt(index,4).toString();
        String Phone = model.getValueAt(index,5).toString();
        String Address = model.getValueAt(index,6).toString();
        String createDateTime = model.getValueAt(index,7).toString();
        String lastUpdateDateTime = model.getValueAt(index,8).toString();
        
        //option = 2 
//        SearchPatient go through to the modifypatient
        int option = 2;
        ModifyPatient patient = new ModifyPatient(user,ID,IC,Name,Gender,Age,Phone,Address,createDateTime,lastUpdateDateTime, option);
        patient.setVisible(true);
        this.dispose();
        /*patient.setVisible(true);
        patient.setLocationRelativeTo(null);
        patient.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        patient.txtID.setEnabled(false);
        patient.btnFind.setEnabled(false);
        patient.txtID.setText(ID);
        patient.txtIC.setText(IC);
        patient.txtName.setText(Name);
        patient.txtGender.setText(Gender);
        patient.txtAge.setText(Age);
        patient.txtPhone.setText(Phone);
        patient.txtAddress.setText(Address);*/
        
    }//GEN-LAST:event_tblPatientMouseClicked

    private void txtIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyPressed
        try {
            // TODO add your handling code here:
            String ID = txtID.getText();
            show_selected_patients("ID",ID);
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(rootPane, "SearchPatient.txtIDPressed get error on line 276, "+ex.getMessage());
        }
    }//GEN-LAST:event_txtIDKeyPressed

    private void txtICKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtICKeyPressed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String IC = txtIC.getText();
            show_selected_patients("IC",IC);
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(rootPane, "SearchPatient.txtICKeyPressed get error on line 287, "+ex.getMessage());
        }
    }//GEN-LAST:event_txtICKeyPressed

    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String Name = txtName.getText();
            show_selected_patients("name",Name);
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(rootPane, "SearchPatient.txtNameKeyPressed get error on line 298, "+ex.getMessage());
        }
    }//GEN-LAST:event_txtNameKeyPressed

    private void txtGenderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGenderKeyPressed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String gender = txtGender.getText();
            show_selected_patients("gender",gender);
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(rootPane, "SearchPatient.txtGenderKeyPressed get error on line 309, "+ex.getMessage());
        }
    }//GEN-LAST:event_txtGenderKeyPressed

    private void txtAgeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyPressed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String age = txtAge.getText();
            show_selected_patients("age",age);
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(rootPane, "SearchPatient.txtAgeKeyPressed get error on line 320, "+ex.getMessage());
        }
    }//GEN-LAST:event_txtAgeKeyPressed

    private void txtPhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyPressed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String phone = txtPhone.getText();
            show_selected_patients("phone",phone);
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(rootPane, "SearchPatient.txtPhoneKeyPressed get error on line 331, "+ex.getMessage());
        }
    }//GEN-LAST:event_txtPhoneKeyPressed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        PatientDetailMenu detail = new PatientDetailMenu(user);
        detail.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        try {
            // TODO add your handling code here:
            String ID = txtID.getText();
            String IC = txtIC.getText();
            String Name = txtName.getText();
            String Gender = txtGender.getText();
            String Age = txtAge.getText();
            String Phone = txtPhone.getText();
            
            show_all_patients(ID, IC, Name, Gender, Age,Phone);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "SearchPatient.btnFindActionPerformed get error on line 354, "+ex.getMessage());
        }
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        try {
            tblPatient.print();
            // TODO add your handling code here:
            /*model = (DefaultTableModel) tblPatient.getModel();
            
            StringBuilder builder = new StringBuilder();
            builder.append("\t 杏生堂药行 \n");
            builder.append("\t Heng Seng Tong Medicall Hall \n");
            builder.append("\t 107, Jalan PKS2, Pekan Simpang Kuala \n");
            builder.append("\t 05400 Alor Setar, Kedah \n");
            MessageFormat header = new MessageFormat(builder.toString());
            
            JTable table = new JTable(model) {
                @Override
                public Printable getPrintable(JTable.PrintMode printMode, MessageFormat headerFormat, MessageFormat footerFormat) {
                    return new TablePrintable(tblPatient, JTable.PrintMode.FIT_WIDTH, header, footerFormat);
                }
            };
            
            
            table.print();*/
            } catch (PrinterException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchPatient().setVisible(true);
            }
        });
    }
    
    public void show_patients() throws SQLException{
         
         Patient patient = new Patient();
         List<Patient> patientList = new ArrayList<Patient>();
         patientList = patient.getPatients();
         model = (DefaultTableModel)tblPatient.getModel();
         Object row[] = new Object[9];
         for(int i =0; i<patientList.size(); i++)
         {
             row[0] = patientList.get(i).getID();
             row[1] = patientList.get(i).getIC();
             row[2] = patientList.get(i).getName();
             row[3] = patientList.get(i).getGender();
             row[4] = patientList.get(i).getAge();
             row[5] = patientList.get(i).getPhone();
             row[6] = patientList.get(i).getAddress();
             row[7] = patientList.get(i).getLastUpdateDateTime();
             row[8] = patientList.get(i).getCreateDateTime();
             model.addRow(row);
         }
    }
    
    public void show_selected_patients(String contribute,String detail) throws SQLException{
        model.setRowCount(0);
        Patient patient = new Patient();
        List<Patient> patientList = new ArrayList<Patient>();
        String arrangement;
        arrangement = comboArrange.getSelectedItem() == "顺序" ? "asc" : comboArrange.getSelectedItem() == "逆序" ? "desc" : "系统有问题！";
        patientList = patient.getDetail(contribute,detail,arrangement);
        model = (DefaultTableModel)tblPatient.getModel();
        Object row[] = new Object[9];
        for(int i =0; i<patientList.size(); i++)
        {
            row[0] = patientList.get(i).getID();
            row[1] = patientList.get(i).getIC();
            row[2] = patientList.get(i).getName();
            row[3] = patientList.get(i).getGender();
            row[4] = patientList.get(i).getAge();
            row[5] = patientList.get(i).getPhone();
            row[6] = patientList.get(i).getAddress();
            row[7] = patientList.get(i).getLastUpdateDateTime();
            row[8] = patientList.get(i).getCreateDateTime();
            model.addRow(row);
        }
    }
    
    public void show_all_patients(String ID, String IC, String Name, String Gender, String Age, String Phone) throws SQLException{
        model.setRowCount(0);
        Patient patient = new Patient();
        List<Patient> patientList = new ArrayList<Patient>();
        String arrangement;
        arrangement = comboArrange.getSelectedItem() == "顺序" ? "asc" : comboArrange.getSelectedItem() == "逆序" ? "desc" : "系统有问题！";
        patientList = patient.getAllDetail(ID, IC, Name, Gender ,Age ,Phone ,arrangement, userid);
        model = (DefaultTableModel)tblPatient.getModel();
        Object row[] = new Object[9];
        for(int i =0; i<patientList.size(); i++)
        {
            row[0] = patientList.get(i).getID();
            row[1] = patientList.get(i).getIC();
            row[2] = patientList.get(i).getName();
            row[3] = patientList.get(i).getGender();
            row[4] = patientList.get(i).getAge();
            row[5] = patientList.get(i).getPhone();
            row[6] = patientList.get(i).getAddress();
            row[7] = patientList.get(i).getLastUpdateDateTime();
            row[8] = patientList.get(i).getCreateDateTime();
            model.addRow(row);
        }
    }
    
    public void image()
    {
        jScrollPane1.getViewport().setBackground(Color.WHITE);
        JTableHeader tableHeader = tblPatient.getTableHeader();
        tableHeader.setFont(new Font("STXihei", Font.BOLD, 18));
        ImageIcon iconLogo = new ImageIcon(getClass().getResource("/menu/hengsengtong.png"));
        lbllogo.setIcon(iconLogo);
        ImageIcon iconBack = new ImageIcon(getClass().getResource("/menu/smallBack.png"));
        btnBack.setIcon(iconBack);
        ImageIcon iconFind = new ImageIcon(getClass().getResource("/menu/smallFind.png"));
        btnFind.setIcon(iconFind);
        ImageIcon iconHeader = new ImageIcon(getClass().getResource("/menu/findmedium.png"));
        jLabel9.setIcon(iconHeader);
        ImageIcon iconPrint = new ImageIcon(getClass().getResource("/menu/smallprint.png"));
        btnPrint.setIcon(iconPrint);
        this.lblName.setText(userid);
        setResizable(false);
    }
    
    public void widthTable()
    {
        jScrollPane1.getViewport().setBackground(Color.WHITE);
        JTableHeader tableHeader = tblPatient.getTableHeader();
        tableHeader.setFont(new Font("STXihei", Font.BOLD, 18));
        tblPatient.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        TableColumnModel columnModel = tblPatient.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(100);
        columnModel.getColumn(1).setPreferredWidth(200);
        columnModel.getColumn(2).setPreferredWidth(200);
        columnModel.getColumn(3).setPreferredWidth(100);
        columnModel.getColumn(4).setPreferredWidth(100);
        columnModel.getColumn(5).setPreferredWidth(200);
        columnModel.getColumn(6).setPreferredWidth(1000);
        columnModel.getColumn(7).setPreferredWidth(200);
        columnModel.getColumn(8).setPreferredWidth(200);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnPrint;
    private javax.swing.JComboBox<String> comboArrange;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JTable tblPatient;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtIC;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
