/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import javaClass.User;
import javaClass.Medicine;
import java.awt.Font;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Sheng
 */
public class SearchMedical extends javax.swing.JFrame {

    /**
     * Creates new form SearchMedical
     */
    private User user;
    DefaultTableModel model;
    public SearchMedical() {
        initComponents();
    }

    public SearchMedical(User user) {
        initComponents();
        this.user = user;
        createColumns();
        show_all_medical();
        JTableHeader tableHeader = tblMedicine.getTableHeader();
        tableHeader.setFont(new Font("STXihei", Font.BOLD, 18));
        setResizable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMedicine = new javax.swing.JTable();
        txtName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMedicine = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCost = new javax.swing.JTextField();
        txtScoop = new javax.swing.JTextField();
        txtEffect = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtComponent = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtIndication = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tblMedicine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblMedicine);

        jScrollPane2.setViewportView(jScrollPane1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(70, 90, 970, 410);

        txtName.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
        });
        getContentPane().add(txtName);
        txtName.setBounds(710, 520, 330, 40);

        jLabel1.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel1.setText("药:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 520, 120, 40);

        jLabel2.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel2.setText("名字:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(570, 520, 80, 40);

        txtMedicine.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        txtMedicine.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMedicineKeyPressed(evt);
            }
        });
        getContentPane().add(txtMedicine);
        txtMedicine.setBounds(180, 520, 330, 40);

        jLabel3.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel3.setText("组成/药性:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 580, 100, 40);

        jLabel4.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel4.setText("主治:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(570, 580, 44, 40);

        jLabel5.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel5.setText("功效:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 740, 50, 40);

        jLabel6.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel6.setText("每次每日分量:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(570, 740, 120, 40);

        jLabel7.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel7.setText("重量:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 800, 60, 40);

        jLabel8.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel8.setText("本钱:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(570, 800, 50, 40);

        jLabel9.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel9.setText("价格:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(70, 860, 60, 30);

        txtCost.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        txtCost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCostKeyPressed(evt);
            }
        });
        getContentPane().add(txtCost);
        txtCost.setBounds(710, 800, 330, 40);

        txtScoop.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        txtScoop.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtScoopKeyPressed(evt);
            }
        });
        getContentPane().add(txtScoop);
        txtScoop.setBounds(710, 740, 330, 40);

        txtEffect.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        txtEffect.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEffectKeyPressed(evt);
            }
        });
        getContentPane().add(txtEffect);
        txtEffect.setBounds(180, 740, 330, 40);

        txtWeight.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        txtWeight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtWeightKeyPressed(evt);
            }
        });
        getContentPane().add(txtWeight);
        txtWeight.setBounds(180, 800, 330, 40);

        txtPrice.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPriceKeyPressed(evt);
            }
        });
        getContentPane().add(txtPrice);
        txtPrice.setBounds(180, 860, 330, 40);

        btnBack.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        btnBack.setText("退出");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(70, 950, 110, 50);

        btnFind.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        btnFind.setText("寻找");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        getContentPane().add(btnFind);
        btnFind.setBounds(930, 950, 110, 50);

        jLabel10.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        jLabel10.setText("寻找药物");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(490, 20, 120, 60);

        txtComponent.setColumns(20);
        txtComponent.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        txtComponent.setRows(5);
        txtComponent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtComponentKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(txtComponent);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(180, 580, 330, 136);

        txtIndication.setColumns(20);
        txtIndication.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        txtIndication.setRows(5);
        txtIndication.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIndicationKeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(txtIndication);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(710, 580, 330, 136);

        setBounds(0, 0, 1123, 1089);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        MedicalDetailMenu menu = new MedicalDetailMenu(user);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtMedicineKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMedicineKeyPressed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String medicine = txtMedicine.getText();
            show_selected_medical("medicine",medicine,"");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_txtMedicineKeyPressed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFindActionPerformed

    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String name = txtName.getText();
            show_selected_medical("name",name,"");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_txtNameKeyPressed

    private void txtComponentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtComponentKeyPressed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String component = txtComponent.getText();
            show_selected_medical("component",component,"property");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_txtComponentKeyPressed

    private void txtIndicationKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIndicationKeyPressed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String indication = txtIndication.getText();
            show_selected_medical("indications",indication,"appliance");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_txtIndicationKeyPressed

    private void txtEffectKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEffectKeyPressed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String effect = txtEffect.getText();
            show_selected_medical("effect",effect,"");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_txtEffectKeyPressed

    private void txtScoopKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtScoopKeyPressed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String scoop = txtScoop.getText();
            show_selected_medical("scoop",scoop,"");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_txtScoopKeyPressed

    private void txtWeightKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWeightKeyPressed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String weight = txtWeight.getText();
            show_selected_medical("gram",weight,"");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_txtWeightKeyPressed

    private void txtCostKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCostKeyPressed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String cost = txtCost.getText();
            show_selected_medical("cost",cost,"");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_txtCostKeyPressed

    private void txtPriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyPressed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String sellprice = txtPrice.getText();
            show_selected_medical("sellprice",sellprice,"");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_txtPriceKeyPressed

    
    private void createColumns()
    {
        model = (DefaultTableModel) tblMedicine.getModel();
        model.addColumn("药");
        model.addColumn("名字");
        model.addColumn("组成/药性");
        model.addColumn("主治/应用");
        model.addColumn("功效");
        model.addColumn("每次每日分量");
        model.addColumn("重量");
        model.addColumn("本钱");
        model.addColumn("价格");
    }
    
    public void show_selected_medical(String contribute,String detail, String contribute1) throws SQLException{
        model.setRowCount(0);
        Medicine medicine = new Medicine();
        List<Medicine> medicineList = new ArrayList<Medicine>();
        medicineList = medicine.getDetail(contribute,detail,contribute1);
        model = (DefaultTableModel)tblMedicine.getModel();
        Object row[] = new Object[9];
        for(int i =0; i<medicineList.size(); i++)
        {
            row[0] = medicineList.get(i).getMedicine();
            row[1] = medicineList.get(i).getName();
            row[2] = medicineList.get(i).getComponent();
            row[3] = medicineList.get(i).getIndications();
            row[4] = medicineList.get(i).getEffect();
            row[5] = medicineList.get(i).getScoop();
            row[6] = medicineList.get(i).getGram();
            row[7] = medicineList.get(i).getCost();
            row[8] = medicineList.get(i).getSellprice();
            model.addRow(row);
        }
    }
    
    public void show_all_medical()
    {
        try {
            model.setRowCount(0);
            Medicine medicine = new Medicine();
            List<Medicine> medicineList = new ArrayList<Medicine>();
            medicineList = medicine.getAllDetail();
            model = (DefaultTableModel)tblMedicine.getModel();
            Object row[] = new Object[9];
            for(int i =0; i<medicineList.size(); i++)
            {
                row[0] = medicineList.get(i).getMedicine();
                row[1] = medicineList.get(i).getName();
                row[2] = medicineList.get(i).getComponent();
                row[3] = medicineList.get(i).getIndications();
                row[4] = medicineList.get(i).getEffect();
                row[5] = medicineList.get(i).getScoop();
                row[6] = medicineList.get(i).getGram();
                row[7] = medicineList.get(i).getCost();
                row[8] = medicineList.get(i).getSellprice();
                model.addRow(row);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchMedical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchMedical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchMedical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchMedical.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchMedical().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnFind;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblMedicine;
    private javax.swing.JTextArea txtComponent;
    private javax.swing.JTextField txtCost;
    private javax.swing.JTextField txtEffect;
    private javax.swing.JTextArea txtIndication;
    private javax.swing.JTextField txtMedicine;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtScoop;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
