/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.Color;
import java.awt.Component;
import javaClass.Prescription;
import javaClass.TablePrintable;
import javaClass.User;
import java.awt.Font;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.List;
import javaClass.Bill;
import javaClass.Excel;
import javaClass.WordWrapCellRenderer;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.standard.MediaPrintableArea;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Sheng
 */
public class ViewDiseaseDetail extends javax.swing.JFrame {

    /**
     * Creates new form ViewDiseaseDetail
     */
    private User user;
    private String from="";
    private String to="";
    private String initialIC="";
    private String initialID="";
    DefaultTableModel model ;
    private String userid = "";
    
    public ViewDiseaseDetail() {
        initComponents();
    }

    public ViewDiseaseDetail(User user, String from, String to, String initialIC, String initialID) throws SQLException
    {
        initComponents();
        this.user = user;
        this.from = from;
        this.to = to;
        this.initialIC = initialIC;
        this.initialID = initialID;
        userid = user.getUserid();
        createColumns();
        show_patient();
        this.lblName.setText(userid);
        JTableHeader tableHeader = tblDisease.getTableHeader();
        tableHeader.setFont(new Font("STXihei", Font.BOLD, 18));
        //setResizable(false);
        widthTable();
        color_table();
        image();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        lbllogo = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        headerPatient = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDisease = new javax.swing.JTable();
        btnPrint = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnExcel = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel5.setLayout(null);

        panelHeader.setBackground(new java.awt.Color(255, 204, 204));
        panelHeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        panelHeader.setForeground(new java.awt.Color(153, 153, 153));
        panelHeader.setLayout(null);
        panelHeader.add(lbllogo);
        lbllogo.setBounds(14, 2, 231, 70);

        jLabel13.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        jLabel13.setText("登入：");
        panelHeader.add(jLabel13);
        jLabel13.setBounds(1160, 0, 75, 70);

        lblName.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        panelHeader.add(lblName);
        lblName.setBounds(1240, 0, 127, 70);

        headerPatient.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        headerPatient.setText("病症资料");
        panelHeader.add(headerPatient);
        headerPatient.setBounds(450, 0, 230, 70);

        jPanel5.add(panelHeader);
        panelHeader.setBounds(0, 0, 1370, 70);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        jPanel2.setLayout(null);

        tblDisease.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        tblDisease.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "IC", "病人名字", "性别", "年龄", "电话号码", "地址", "主症", "病症分类", "脉象", "舌质", "舌苔", "大小便", "病史", "体温", "血压", "处方", "药物分类", "参考病症", "药物名称", "剂量", "价格/G", "总价值", "创建时间", "更新时间", "病症ID", "处方ID", "Bill", "最新", "initialweight"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDisease.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblDisease.setRowHeight(25);
        tblDisease.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDiseaseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDisease);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(50, 60, 1250, 380);

        btnPrint.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        btnPrint.setText("打印");
        btnPrint.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel2.add(btnPrint);
        btnPrint.setBounds(1520, 710, 150, 60);

        btnBack.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        btnBack.setText("退出");
        btnBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack);
        btnBack.setBounds(1690, 710, 150, 60);

        btnExcel.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        btnExcel.setText("Excel");
        btnExcel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        btnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcelActionPerformed(evt);
            }
        });
        jPanel2.add(btnExcel);
        btnExcel.setBounds(1350, 710, 150, 60);

        jLabel24.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel24.setText("最新资料");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(390, 460, 130, 30);

        jPanel3.setBackground(new java.awt.Color(151, 254, 63));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        jPanel2.add(jPanel3);
        jPanel3.setBounds(350, 460, 30, 30);

        jLabel23.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel23.setText("旧资料");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(90, 460, 130, 30);

        jPanel4.setBackground(new java.awt.Color(254, 115, 63));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        jPanel2.add(jPanel4);
        jPanel4.setBounds(50, 460, 30, 30);

        jPanel5.add(jPanel2);
        jPanel2.setBounds(30, 100, 1330, 530);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("CopyRight © Heng Seng Tong");
        jPanel6.add(jLabel14);

        jPanel5.add(jPanel6);
        jPanel6.setBounds(0, 650, 1370, 50);

        jScrollPane2.setViewportView(jPanel5);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(0, 0, 1370, 700);

        setBounds(0, 0, 1386, 746);
    }// </editor-fold>//GEN-END:initComponents

    private void tblDiseaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDiseaseMouseClicked
        try {
            // TODO add your handling code here:
            model = (DefaultTableModel) tblDisease.getModel();
            int index = tblDisease.getSelectedRow();
            TableModel model = tblDisease.getModel();
            int column = tblDisease.getSelectedColumn();
            String ID = model.getValueAt(index, 0).toString();
            String IC = model.getValueAt(index,1).toString();
            String Name = model.getValueAt(index,2).toString();
            String Gender = model.getValueAt(index,3).toString();
            String Age = model.getValueAt(index,4).toString();
            String Phone = model.getValueAt(index,5).toString();
            String Address = model.getValueAt(index,6).toString();
            String Symptom = model.getValueAt(index,7).toString();
            String Category = model.getValueAt(index,8).toString();
            String PulseCondition = model.getValueAt(index,9).toString();
            String TongueQuality = model.getValueAt(index,10).toString();
            String TongueCoating = model.getValueAt(index,11).toString();
            String PeeShit = model.getValueAt(index,12).toString();
            String History = model.getValueAt(index,13).toString();
            String Temperature = model.getValueAt(index,14).toString();
            String BloodPressure = model.getValueAt(index,15).toString();
            String Chufang = model.getValueAt(index,16).toString();
            String CategoryTable = model.getValueAt(index,17).toString();
            String Reference = model.getValueAt(index,18).toString();
            String NameTable = model.getValueAt(index,19).toString();
            String Jiliang = model.getValueAt(index,20).toString();
            String Price = model.getValueAt(index,21).toString();
            String TotalPrice = model.getValueAt(index,22).toString();
            String CreateDateTime = model.getValueAt(index,23).toString();
            String LastUpdateDateTime = model.getValueAt(index,24).toString();
            String DiseaseID = model.getValueAt(index,25).toString();
            String PrescriptionID = model.getValueAt(index,26).toString();
            String BillNo = model.getValueAt(index,27).toString();
            String latest = model.getValueAt(index,28).toString();
            String initialweight = model.getValueAt(index,29).toString();
            List<Bill> billList = new ArrayList<Bill>();
            Bill billNo = new Bill();
            billList = billNo.getBillsDetail(userid, "BillNo",BillNo);
            String subtotal = String.valueOf(billList.get(0).getSubtotal());
            
            int option =5;
            
            if (column >= 0 && column <= 6)
            {
                ModifyPatient patient = new ModifyPatient(user,ID,IC,Name,Gender,Age,Phone,Address,CreateDateTime,LastUpdateDateTime, option, from, to, initialIC, initialID);
                patient.setVisible(true);
                this.dispose();
            }
            else if(column >= 7 && column <= 15)
            {
                try {
                    ModifyDisease disease = new ModifyDisease(user,ID,IC,Name,Phone,DiseaseID,Symptom,Category,PulseCondition,TongueQuality,TongueCoating,PeeShit,History,Temperature,BloodPressure, from, to, initialIC, initialID, option);
                    disease.setVisible(true);
                    this.dispose();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
            else
            {
                try {
                    ModifyChuFang chufang = new ModifyChuFang(user,ID,IC,Name,Phone,PrescriptionID,Chufang,CategoryTable,Reference,NameTable,Jiliang,Price,TotalPrice,initialweight,latest,BillNo,subtotal,DiseaseID,from,to,initialIC,initialID,option);
                    chufang.setVisible(true);
                    this.dispose();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_tblDiseaseMouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        MonthYearIC ic = new MonthYearIC(user,5);
        ic.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        //Option 1: Cannot fitwidth and header too messy
        /*try {
            // TODO add your handling code here:
        /*    HashPrintRequestAttributeSet attr = new HashPrintRequestAttributeSet();
            attr.add(new MediaPrintableArea(500f, 1000f, 750/72f, 1000/72f, MediaPrintableArea.INCH));       

            PrinterJob job = PrinterJob.getPrinterJob();
            
            MessageFormat[] header = new MessageFormat[3];

            header[0] = new MessageFormat("");
            header[1] = new MessageFormat("zhe sheng tang" );
            header[2] = new MessageFormat("                  n" );

            MessageFormat[] footer = new MessageFormat[2];
            footer[0] = new MessageFormat("");
            footer[1] = new MessageFormat("-{1}-");
            //job.print(attr);
            job.setPrintable(new MyTablePrintable(tblDisease, JTable.PrintMode.FIT_WIDTH, header, footer));
            job.printDialog();
            job.print();
        } catch (PrinterException ex) {
            ex.printStackTrace();
        }*/
        
        
        //Option 2: Cannot change the font size for jtable
        try {
            // TODO add your handling code here:
            model = (DefaultTableModel) tblDisease.getModel();
            
            StringBuilder builder = new StringBuilder();
            builder.append("\t 杏生堂药行 \n");
            builder.append("\t Heng Seng Tong Medicall Hall \n");
            builder.append("\t 107, Jalan PKS2, Pekan Simpang Kuala \n");
            builder.append("\t 05400 Alor Setar, Kedah \n");
            MessageFormat header = new MessageFormat(builder.toString());
            
            JTable table = new JTable(model) {
                @Override
                public Printable getPrintable(JTable.PrintMode printMode, MessageFormat headerFormat, MessageFormat footerFormat) {
                    return new TablePrintable(tblDisease, JTable.PrintMode.FIT_WIDTH, header, footerFormat);
                }
            };
            
            
            table.print();
        
        //Option 3: use text area
          /*  StringBuilder builder = new StringBuilder();
            builder.append("\t\t 杏生堂药行 \n");
            builder.append("\t\t Heng Seng Tong Medicall Hall \n");
            builder.append("\t 107, Jalan PKS2, Pekan Simpang Kuala \n");
            builder.append("\t 05400 Alor Setar, Kedah \n");
            builder.append("----------------------------------------------------------------------------------------------------------------------\n");
            builder.append("ID\t\t");
            builder.append("IC\t\t");
            builder.append("病人名字\t\t");
            builder.append("性别\t\t");
            builder.append("年龄\t\t");
            builder.append("电话号码\t\t");
            builder.append("主症\t\t");
            builder.append("病症分类\t\t");
            builder.append("脉象\t\t");
            builder.append("舌质\t\t");
            builder.append("舌苔\t\t");
            builder.append("大小便\t\t");
            builder.append("病史\t\t");
            builder.append("体温\t\t");
            builder.append("血压\t\t");
            builder.append("处方\t\t");
            builder.append("药物种类\t\t");
            builder.append("药物名称\t\t");
            builder.append("剂量\t\t");
            builder.append("价格/G\t\t");
            builder.append("总价值\t\t");
            builder.append("----------------------------------------------------------------------------------------------------------------------\n");
            txtPrint.setText(builder.toString());
            txtPrint.print();*/
        } catch (PrinterException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
        // TODO add your handling code here:
        Excel exc = new Excel();
        int result = 0;
        result = exc.countModel(model, "DiseaseDetail");
        if(result == 1)
        {
            JOptionPane.showMessageDialog(rootPane, "转换成功Excel名字叫Storage.xlsx");
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "确保你删掉旧的Storage.xlsx才来转换");
        }
    }//GEN-LAST:event_btnExcelActionPerformed

    
    private void createColumns()
    {
        model = (DefaultTableModel) tblDisease.getModel();
       /* model.addColumn("ID");
        model.addColumn("IC");
        model.addColumn("病人名字");
        model.addColumn("性别");
        model.addColumn("年龄");
        model.addColumn("电话号码");
        model.addColumn("地址");
        model.addColumn("主症");
        model.addColumn("病症分类");
        model.addColumn("脉象");
        model.addColumn("舌质");
        model.addColumn("舌苔");
        model.addColumn("大小便");  
        model.addColumn("病史"); 
        model.addColumn("体温"); 
        model.addColumn("血压"); 
        model.addColumn("处方");
        model.addColumn("药物种类");
        model.addColumn("药物名称");
        model.addColumn("剂量");
        model.addColumn("价格/G");
        model.addColumn("总价值");
        model.addColumn("创建时间");
        model.addColumn("更新时间");
        model.addColumn("病症ID");
        model.addColumn("处方ID");*/
    }
    
    public void show_patient() throws SQLException{
         Prescription prescription = new Prescription();
         List<Prescription> prescriptionList = new ArrayList<Prescription>();
         /*if(option == 3)
         {
             patientList = patient.getPatients();
         }
         else
         {*/
             prescriptionList = prescription.getPrescriptions(from, to, initialIC, initialID,userid);
         //}
         
         model = (DefaultTableModel)tblDisease.getModel();
         Object row[] = new Object[30];
         for(int i =0; i<prescriptionList.size(); i++)
         {
             row[0] = prescriptionList.get(i).getPatientID();
             row[1] = prescriptionList.get(i).getIC();
             row[2] = prescriptionList.get(i).getName();
             row[3] = prescriptionList.get(i).getGender();
             row[4] = prescriptionList.get(i).getAge();
             row[5] = prescriptionList.get(i).getPhone();
             row[6] = prescriptionList.get(i).getAddress();
             row[7] = prescriptionList.get(i).getSymptom();
             row[8] = prescriptionList.get(i).getCategory();
             row[9] = prescriptionList.get(i).getPulseCondition();
             row[10] = prescriptionList.get(i).getTongueQuality();
             row[11] = prescriptionList.get(i).getTongueCoating();
             row[12] = prescriptionList.get(i).getPeeShit();
             row[13] = prescriptionList.get(i).getHistory();
             row[14] = prescriptionList.get(i).getTemperature();
             row[15] = prescriptionList.get(i).getBloodPressure();
             row[16] = prescriptionList.get(i).getChufang();
             row[17] = prescriptionList.get(i).getCategorytable();
             row[18] = prescriptionList.get(i).getReference();
             row[19] = prescriptionList.get(i).getNametable();
             row[20] = prescriptionList.get(i).getJiliang();
             row[21] = prescriptionList.get(i).getPrice();
             row[22] = prescriptionList.get(i).getTotalprice();
             row[23] = prescriptionList.get(i).getCreateDateTime();
             row[24] = prescriptionList.get(i).getLastUpdateDateTime();
             row[25] = prescriptionList.get(i).getDiseaseID();
             row[26] = prescriptionList.get(i).getPrescriptionID();
             row[27] = prescriptionList.get(i).getBillno();
             row[28] = prescriptionList.get(i).getLatest();
             row[29] = prescriptionList.get(i).getInitialWeight();
             model.addRow(row);
         }
    }
    
    public void image()
    {
        jScrollPane1.getViewport().setBackground(Color.WHITE);
        JTableHeader tableHeader = tblDisease.getTableHeader();
        tableHeader.setFont(new Font("STXihei", Font.BOLD, 18));
        ImageIcon iconLogo = new ImageIcon(getClass().getResource("/menu/hengsengtong.png"));
        lbllogo.setIcon(iconLogo);
        ImageIcon iconBack = new ImageIcon(getClass().getResource("/menu/smallBack.png"));
        btnBack.setIcon(iconBack);
        ImageIcon iconPrint = new ImageIcon(getClass().getResource("/menu/smallprint.png"));
        btnPrint.setIcon(iconPrint);
        ImageIcon iconLabel = new ImageIcon(getClass().getResource("/menu/report.png"));
        headerPatient.setIcon(iconLabel);
        ImageIcon iconExcel = new ImageIcon(getClass().getResource("/menu/smallExcel.png"));
        btnExcel.setIcon(iconExcel);
    }
    
    public void color_table()
    {
        tblDisease.setDefaultRenderer(Object.class, new PriorityCellRenderer());
        tblDisease.getTableHeader().setReorderingAllowed(false);
    }
    
    //change the colour
    public class PriorityCellRenderer extends DefaultTableCellRenderer {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {
            super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            int latest = Integer.parseInt(table.getValueAt(row, 28).toString());
            
            if (latest ==  0) {
                setBackground(new Color(254, 115, 63));  // or background
            }
            else
            {
                setBackground(new Color(151, 254, 63));  // or background
            }
            return this;
        }
    }
    
    public void widthTable()
    {
        jScrollPane1.getViewport().setBackground(Color.WHITE);
        JTableHeader tableHeader = tblDisease.getTableHeader();
        tableHeader.setFont(new Font("STXihei", Font.BOLD, 18));
        tblDisease.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        //new JScrollPane(tblMedicine, JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        TableColumnModel columnModel = tblDisease.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(100);
        columnModel.getColumn(1).setPreferredWidth(200);
        columnModel.getColumn(2).setPreferredWidth(200);
        columnModel.getColumn(3).setPreferredWidth(160);
        columnModel.getColumn(4).setPreferredWidth(100);
        columnModel.getColumn(5).setPreferredWidth(200);
        columnModel.getColumn(6).setPreferredWidth(1000);
        columnModel.getColumn(7).setPreferredWidth(200);
        columnModel.getColumn(8).setPreferredWidth(200);
        columnModel.getColumn(9).setPreferredWidth(200);
        columnModel.getColumn(10).setPreferredWidth(200);
        columnModel.getColumn(11).setPreferredWidth(200);
        columnModel.getColumn(12).setPreferredWidth(200);
        columnModel.getColumn(13).setPreferredWidth(200);
        columnModel.getColumn(14).setPreferredWidth(100);
        columnModel.getColumn(15).setPreferredWidth(100);
        columnModel.getColumn(16).setPreferredWidth(100);
        columnModel.getColumn(17).setPreferredWidth(200);
        columnModel.getColumn(18).setPreferredWidth(100);
        columnModel.getColumn(19).setPreferredWidth(200);
        columnModel.getColumn(20).setPreferredWidth(100);
        columnModel.getColumn(21).setPreferredWidth(100);
        columnModel.getColumn(22).setPreferredWidth(200);
        columnModel.getColumn(23).setPreferredWidth(200);
        columnModel.getColumn(24).setPreferredWidth(200);
        columnModel.getColumn(25).setPreferredWidth(200);
        columnModel.getColumn(26).setPreferredWidth(200);
        columnModel.getColumn(27).setPreferredWidth(100);
        columnModel.getColumn(28).setPreferredWidth(50);
        columnModel.getColumn(29).setPreferredWidth(50);
        columnModel.getColumn(28).setMinWidth(0);
        columnModel.getColumn(28).setMaxWidth(0);
        columnModel.getColumn(29).setMinWidth(0);
        columnModel.getColumn(29).setMaxWidth(0);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewDiseaseDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewDiseaseDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewDiseaseDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewDiseaseDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewDiseaseDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnExcel;
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel headerPatient;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JTable tblDisease;
    // End of variables declaration//GEN-END:variables
}
